// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ChartComparison config for multi-series overlays.
 */
export class ChartComparison {
    "baselineComponentId": string;
    "type": string;

    /** Creates a new ChartComparison instance. */
    constructor($$source: Partial<ChartComparison> = {}) {
        if (!("baselineComponentId" in $$source)) {
            this["baselineComponentId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartComparison instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartComparison {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartComparison($$parsedSource as Partial<ChartComparison>);
    }
}

/**
 * ChartTransform enables custom pipelines (resample, moving average, etc.).
 */
export class ChartTransform {
    "kind": string;
    "config": { [_ in string]?: any };

    /** Creates a new ChartTransform instance. */
    constructor($$source: Partial<ChartTransform> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartTransform instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartTransform {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new ChartTransform($$parsedSource as Partial<ChartTransform>);
    }
}

/**
 * ColumnDefinition represents a column in a synthetic view
 */
export class ColumnDefinition {
    "name": string;
    "type": string;

    /** Creates a new ColumnDefinition instance. */
    constructor($$source: Partial<ColumnDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDefinition($$parsedSource as Partial<ColumnDefinition>);
    }
}

/**
 * Report represents a drag-and-drop report definition with layout and components.
 */
export class Report {
    "id": string;
    "name": string;
    "description": string;
    "folder": string;
    "tags": string[];
    "definition": ReportDefinition;
    "filter": ReportFilterDefinition;
    "syncOptions": ReportSyncOptions;
    "starred": boolean;
    "starredAt"?: time$0.Time | null;
    "lastRunAt": time$0.Time | null;
    "lastRunStatus": string;
    "metadata": { [_ in string]?: string };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("definition" in $$source)) {
            this["definition"] = (new ReportDefinition());
        }
        if (!("filter" in $$source)) {
            this["filter"] = (new ReportFilterDefinition());
        }
        if (!("syncOptions" in $$source)) {
            this["syncOptions"] = (new ReportSyncOptions());
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }
        if (!("lastRunAt" in $$source)) {
            this["lastRunAt"] = null;
        }
        if (!("lastRunStatus" in $$source)) {
            this["lastRunStatus"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType4;
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField5_0($$parsedSource["definition"]);
        }
        if ("filter" in $$parsedSource) {
            $$parsedSource["filter"] = $$createField6_0($$parsedSource["filter"]);
        }
        if ("syncOptions" in $$parsedSource) {
            $$parsedSource["syncOptions"] = $$createField7_0($$parsedSource["syncOptions"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField12_0($$parsedSource["metadata"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

/**
 * ReportChartSettings customises graph rendering.
 */
export class ReportChartSettings {
    "variant": string;
    "xField": string;
    "yField": string;
    "series": string[];
    "options": { [_ in string]?: string };
    "comparison"?: ChartComparison | null;
    "transform"?: ChartTransform | null;

    /** Creates a new ReportChartSettings instance. */
    constructor($$source: Partial<ReportChartSettings> = {}) {
        if (!("variant" in $$source)) {
            this["variant"] = "";
        }
        if (!("xField" in $$source)) {
            this["xField"] = "";
        }
        if (!("yField" in $$source)) {
            this["yField"] = "";
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }
        if (!("options" in $$source)) {
            this["options"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportChartSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportChartSettings {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField3_0($$parsedSource["series"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        if ("comparison" in $$parsedSource) {
            $$parsedSource["comparison"] = $$createField5_0($$parsedSource["comparison"]);
        }
        if ("transform" in $$parsedSource) {
            $$parsedSource["transform"] = $$createField6_0($$parsedSource["transform"]);
        }
        return new ReportChartSettings($$parsedSource as Partial<ReportChartSettings>);
    }
}

/**
 * ReportComponent defines a configurable block on a report.
 */
export class ReportComponent {
    "id": string;
    "title": string;
    "description": string;
    "type": ReportComponentType;
    "size": ReportComponentSize;
    "query": ReportQueryConfig;
    "chart"?: ReportChartSettings | null;
    "llm"?: ReportLLMSettings | null;
    "options"?: { [_ in string]?: any };

    /** Creates a new ReportComponent instance. */
    constructor($$source: Partial<ReportComponent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ReportComponentType.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = (new ReportComponentSize());
        }
        if (!("query" in $$source)) {
            this["query"] = (new ReportQueryConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportComponent instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportComponent {
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType15;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("size" in $$parsedSource) {
            $$parsedSource["size"] = $$createField4_0($$parsedSource["size"]);
        }
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField5_0($$parsedSource["query"]);
        }
        if ("chart" in $$parsedSource) {
            $$parsedSource["chart"] = $$createField6_0($$parsedSource["chart"]);
        }
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField7_0($$parsedSource["llm"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new ReportComponent($$parsedSource as Partial<ReportComponent>);
    }
}

/**
 * ReportComponentSize drives the rendered footprint of a component.
 */
export class ReportComponentSize {
    "minW": number;
    "minH": number;
    "maxW": number;
    "maxH": number;

    /** Creates a new ReportComponentSize instance. */
    constructor($$source: Partial<ReportComponentSize> = {}) {
        if (!("minW" in $$source)) {
            this["minW"] = 0;
        }
        if (!("minH" in $$source)) {
            this["minH"] = 0;
        }
        if (!("maxW" in $$source)) {
            this["maxW"] = 0;
        }
        if (!("maxH" in $$source)) {
            this["maxH"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportComponentSize instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportComponentSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportComponentSize($$parsedSource as Partial<ReportComponentSize>);
    }
}

/**
 * ReportComponentType enumerates supported component types.
 */
export enum ReportComponentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReportComponentChart = "chart",
    ReportComponentMetric = "metric",
    ReportComponentTable = "table",
    ReportComponentCombo = "combo",
    ReportComponentLLM = "llm",
};

/**
 * ReportDefinition stores canvas layout metadata and embedded components.
 */
export class ReportDefinition {
    "layout": ReportLayoutSlot[];
    "components": ReportComponent[];

    /** Creates a new ReportDefinition instance. */
    constructor($$source: Partial<ReportDefinition> = {}) {
        if (!("layout" in $$source)) {
            this["layout"] = [];
        }
        if (!("components" in $$source)) {
            this["components"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportDefinition {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField0_0($$parsedSource["layout"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField1_0($$parsedSource["components"]);
        }
        return new ReportDefinition($$parsedSource as Partial<ReportDefinition>);
    }
}

/**
 * ReportFilterDefinition defines a reusable top-level filter bar.
 */
export class ReportFilterDefinition {
    "fields": ReportFilterField[];

    /** Creates a new ReportFilterDefinition instance. */
    constructor($$source: Partial<ReportFilterDefinition> = {}) {
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportFilterDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportFilterDefinition {
        const $$createField0_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField0_0($$parsedSource["fields"]);
        }
        return new ReportFilterDefinition($$parsedSource as Partial<ReportFilterDefinition>);
    }
}

/**
 * ReportFilterField represents a single interactive filter control.
 */
export class ReportFilterField {
    "key": string;
    "label": string;
    "type": string;
    "defaultValue": any;
    "required": boolean;
    "choices": string[];

    /** Creates a new ReportFilterField instance. */
    constructor($$source: Partial<ReportFilterField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = null;
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("choices" in $$source)) {
            this["choices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportFilterField instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportFilterField {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("choices" in $$parsedSource) {
            $$parsedSource["choices"] = $$createField5_0($$parsedSource["choices"]);
        }
        return new ReportFilterField($$parsedSource as Partial<ReportFilterField>);
    }
}

/**
 * ReportLLMSettings encapsulates prompt + provider metadata.
 */
export class ReportLLMSettings {
    "provider": string;
    "model": string;
    "promptTemplate": string;
    "contextComponents": string[];
    "temperature": number;
    "maxTokens": number;
    "metadata": { [_ in string]?: string };

    /** Creates a new ReportLLMSettings instance. */
    constructor($$source: Partial<ReportLLMSettings> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("promptTemplate" in $$source)) {
            this["promptTemplate"] = "";
        }
        if (!("contextComponents" in $$source)) {
            this["contextComponents"] = [];
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportLLMSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportLLMSettings {
        const $$createField3_0 = $$createType1;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextComponents" in $$parsedSource) {
            $$parsedSource["contextComponents"] = $$createField3_0($$parsedSource["contextComponents"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField6_0($$parsedSource["metadata"]);
        }
        return new ReportLLMSettings($$parsedSource as Partial<ReportLLMSettings>);
    }
}

/**
 * ReportLayoutSlot defines a single area on the report canvas.
 */
export class ReportLayoutSlot {
    "componentId": string;
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /** Creates a new ReportLayoutSlot instance. */
    constructor($$source: Partial<ReportLayoutSlot> = {}) {
        if (!("componentId" in $$source)) {
            this["componentId"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportLayoutSlot instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportLayoutSlot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportLayoutSlot($$parsedSource as Partial<ReportLayoutSlot>);
    }
}

/**
 * ReportQueryConfig encapsulates SQL or builder state for component queries.
 */
export class ReportQueryConfig {
    "mode": ReportQueryMode;
    "connectionId": string;
    "sql": string;
    "builderState": json$0.RawMessage;
    "queryIr": json$0.RawMessage;
    "useFederation": boolean;
    "limit": number | null;
    "cacheSeconds": number;
    "topLevelFilter": string[];
    "parameters": { [_ in string]?: any };

    /** Creates a new ReportQueryConfig instance. */
    constructor($$source: Partial<ReportQueryConfig> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = ReportQueryMode.$zero;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("builderState" in $$source)) {
            this["builderState"] = null;
        }
        if (!("queryIr" in $$source)) {
            this["queryIr"] = null;
        }
        if (!("useFederation" in $$source)) {
            this["useFederation"] = false;
        }
        if (!("limit" in $$source)) {
            this["limit"] = null;
        }
        if (!("cacheSeconds" in $$source)) {
            this["cacheSeconds"] = 0;
        }
        if (!("topLevelFilter" in $$source)) {
            this["topLevelFilter"] = [];
        }
        if (!("parameters" in $$source)) {
            this["parameters"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportQueryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportQueryConfig {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topLevelFilter" in $$parsedSource) {
            $$parsedSource["topLevelFilter"] = $$createField8_0($$parsedSource["topLevelFilter"]);
        }
        if ("parameters" in $$parsedSource) {
            $$parsedSource["parameters"] = $$createField9_0($$parsedSource["parameters"]);
        }
        return new ReportQueryConfig($$parsedSource as Partial<ReportQueryConfig>);
    }
}

/**
 * ReportQueryMode indicates how data is sourced for a component.
 */
export enum ReportQueryMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReportQueryModeSQL = "sql",
    ReportQueryModeBuilder = "builder",
};

/**
 * ReportSummary contains lightweight metadata for listing views.
 */
export class ReportSummary {
    "id": string;
    "name": string;
    "description": string;
    "folder": string;
    "tags": string[];
    "starred": boolean;
    "starredAt"?: time$0.Time | null;
    "updatedAt": time$0.Time;
    "lastRunAt": time$0.Time | null;
    "lastRunStatus": string;

    /** Creates a new ReportSummary instance. */
    constructor($$source: Partial<ReportSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("lastRunAt" in $$source)) {
            this["lastRunAt"] = null;
        }
        if (!("lastRunStatus" in $$source)) {
            this["lastRunStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportSummary {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new ReportSummary($$parsedSource as Partial<ReportSummary>);
    }
}

/**
 * ReportSyncOptions configures background refresh & sync.
 */
export class ReportSyncOptions {
    "enabled": boolean;
    "cadence": string;
    "target": string;

    /** Creates a new ReportSyncOptions instance. */
    constructor($$source: Partial<ReportSyncOptions> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("cadence" in $$source)) {
            this["cadence"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSyncOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportSyncOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportSyncOptions($$parsedSource as Partial<ReportSyncOptions>);
    }
}

/**
 * SourceDefinition represents a source table for a synthetic view
 */
export class SourceDefinition {
    "connectionIdOrName": string;
    "schema": string;
    "table": string;

    /** Creates a new SourceDefinition instance. */
    constructor($$source: Partial<SourceDefinition> = {}) {
        if (!("connectionIdOrName" in $$source)) {
            this["connectionIdOrName"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceDefinition($$parsedSource as Partial<SourceDefinition>);
    }
}

/**
 * ViewDefinition represents the structure of a synthetic view definition
 */
export class ViewDefinition {
    "id": string;
    "name": string;
    "description": string;
    "version": string;
    "columns": ColumnDefinition[];

    /**
     * JSON representation of QueryIR
     */
    "ir": { [_ in string]?: any };
    "sources": SourceDefinition[];
    "compiledDuckDBSQL": string;
    "options": ViewOptions;

    /** Creates a new ViewDefinition instance. */
    constructor($$source: Partial<ViewDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("ir" in $$source)) {
            this["ir"] = {};
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("compiledDuckDBSQL" in $$source)) {
            this["compiledDuckDBSQL"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new ViewOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ViewDefinition {
        const $$createField4_0 = $$createType23;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType25;
        const $$createField8_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("ir" in $$parsedSource) {
            $$parsedSource["ir"] = $$createField5_0($$parsedSource["ir"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField6_0($$parsedSource["sources"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new ViewDefinition($$parsedSource as Partial<ViewDefinition>);
    }
}

/**
 * ViewOptions contains configuration options for a synthetic view
 */
export class ViewOptions {
    "rowLimitDefault": number;
    "materializeTemp": boolean;

    /** Creates a new ViewOptions instance. */
    constructor($$source: Partial<ViewOptions> = {}) {
        if (!("rowLimitDefault" in $$source)) {
            this["rowLimitDefault"] = 0;
        }
        if (!("materializeTemp" in $$source)) {
            this["materializeTemp"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ViewOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViewOptions($$parsedSource as Partial<ViewOptions>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ReportDefinition.createFrom;
const $$createType3 = ReportFilterDefinition.createFrom;
const $$createType4 = ReportSyncOptions.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = ChartComparison.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = ChartTransform.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = ReportComponentSize.createFrom;
const $$createType11 = ReportQueryConfig.createFrom;
const $$createType12 = ReportChartSettings.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = ReportLLMSettings.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = ReportLayoutSlot.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ReportComponent.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ReportFilterField.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ColumnDefinition.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = SourceDefinition.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = ViewOptions.createFrom;
