// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "./backend-go/pkg/catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./backend-go/pkg/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemadiff$0 from "./backend-go/pkg/schemadiff/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./backend-go/pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} key
 * @param {services$0.KeyboardAction} action
 * @returns {$CancellablePromise<void>}
 */
export function AddKeyboardBinding(key, action) {
    return $Call.ByID(1690460790, key, action);
}

/**
 * AssignTableSteward assigns a steward to a table
 * @param {string} tableID
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function AssignTableSteward(tableID, userID) {
    return $Call.ByID(2965256544, tableID, userID);
}

/**
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function CancelQueryStream(streamID) {
    return $Call.ByID(2170939209, streamID);
}

/**
 * CheckBiometricAvailability checks if biometric authentication is available on the current platform
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function CheckBiometricAvailability() {
    return $Call.ByID(2714630900).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CheckForUpdates checks if a new version is available
 * @returns {$CancellablePromise<$models.UpdateInfo | null>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CheckStoredToken checks if a valid token exists for the specified provider
 * @param {string} provider
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckStoredToken(provider) {
    return $Call.ByID(128319793, provider);
}

/**
 * ClearAIMemorySessions removes stored AI memory sessions
 * @returns {$CancellablePromise<void>}
 */
export function ClearAIMemorySessions() {
    return $Call.ByID(1536711826);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearRecentFiles() {
    return $Call.ByID(1785700092);
}

/**
 * CompareConnectionSchemas compares schemas between two database connections
 * @param {string} sourceConnID
 * @param {string} targetConnID
 * @returns {$CancellablePromise<schemadiff$0.SchemaDiff | null>}
 */
export function CompareConnectionSchemas(sourceConnID, targetConnID) {
    return $Call.ByID(597386636, sourceConnID, targetConnID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CompareWithSnapshot compares a live connection against a saved snapshot
 * @param {string} connectionID
 * @param {string} snapshotID
 * @returns {$CancellablePromise<schemadiff$0.SchemaDiff | null>}
 */
export function CompareWithSnapshot(connectionID, snapshotID) {
    return $Call.ByID(3100980528, connectionID, snapshotID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ConfigureAIProvider configures an AI provider dynamically from UI
 * @param {$models.ProviderConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureAIProvider(config) {
    return $Call.ByID(3568717316, config);
}

/**
 * @param {string} srcPath
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function CopyFile(srcPath, destPath) {
    return $Call.ByID(2847719802, srcPath, destPath);
}

/**
 * CreateCatalogTag creates a new custom tag
 * @param {catalog$0.CatalogTag | null} tag
 * @returns {$CancellablePromise<void>}
 */
export function CreateCatalogTag(tag) {
    return $Call.ByID(3009123336, tag);
}

/**
 * CreateColumnCatalogEntry creates a new column catalog entry
 * @param {catalog$0.ColumnCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function CreateColumnCatalogEntry(entry) {
    return $Call.ByID(1664831794, entry);
}

/**
 * CreateConnection creates a new database connection
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<$models.ConnectionInfo | null>}
 */
export function CreateConnection(req) {
    return $Call.ByID(1454115897, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function CreateDirectory(dirPath) {
    return $Call.ByID(148843624, dirPath);
}

/**
 * CreateSchemaSnapshot creates a point-in-time snapshot of a database schema
 * @param {string} connectionID
 * @param {string} name
 * @returns {$CancellablePromise<schemadiff$0.SnapshotMetadata | null>}
 */
export function CreateSchemaSnapshot(connectionID, name) {
    return $Call.ByID(3392473098, connectionID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * CreateTableCatalogEntry creates a new table entry in the catalog
 * @param {catalog$0.TableCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function CreateTableCatalogEntry(entry) {
    return $Call.ByID(1692805770, entry);
}

/**
 * @param {string} content
 * @param {string} prefix
 * @param {string} suffix
 * @returns {$CancellablePromise<string>}
 */
export function CreateTempFile(content, prefix, suffix) {
    return $Call.ByID(3065376313, content, prefix, suffix);
}

/**
 * DeleteAIMemorySession removes a single session by ID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAIMemorySession(sessionID) {
    return $Call.ByID(1808371517, sessionID);
}

/**
 * DeleteCatalogTag deletes a custom tag
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCatalogTag(id) {
    return $Call.ByID(2492557543, id);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(filePath) {
    return $Call.ByID(2962294020, filePath);
}

/**
 * DeletePassword removes a password from both storage locations
 * connectionID is used as the identifier for the stored credential
 * Does not return an error if the password doesn't exist
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePassword(connectionID) {
    return $Call.ByID(773177391, connectionID);
}

/**
 * DeleteQueryRows deletes one or more rows via editable metadata guarantees
 * @param {$models.QueryRowDeleteRequest} req
 * @returns {$CancellablePromise<$models.QueryRowDeleteResponse | null>}
 */
export function DeleteQueryRows(req) {
    return $Call.ByID(1819062243, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * DeleteReport removes a report definition.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteReport(id) {
    return $Call.ByID(1620331128, id);
}

/**
 * DeleteSchemaSnapshot deletes a saved snapshot
 * @param {string} snapshotID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSchemaSnapshot(snapshotID) {
    return $Call.ByID(3026201829, snapshotID);
}

/**
 * DeleteSyntheticView deletes a synthetic view by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSyntheticView(id) {
    return $Call.ByID(573931472, id);
}

/**
 * DeleteTableCatalogEntry deletes a table catalog entry
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTableCatalogEntry(id) {
    return $Call.ByID(1639720475, id);
}

/**
 * DeleteWebAuthnCredential removes a WebAuthn credential for a user
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWebAuthnCredential(userID) {
    return $Call.ByID(3729908773, userID);
}

/**
 * ExecuteMultiDatabaseQuery executes a query that spans multiple database connections
 * @param {$models.MultiQueryRequest} req
 * @returns {$CancellablePromise<$models.MultiQueryResponse | null>}
 */
export function ExecuteMultiDatabaseQuery(req) {
    return $Call.ByID(3185941324, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ExecuteQuery executes a SQL query
 * @param {$models.QueryRequest} req
 * @returns {$CancellablePromise<$models.QueryResponse | null>}
 */
export function ExecuteQuery(req) {
    return $Call.ByID(2868660388, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * Database Service Methods
 * @param {string} connectionID
 * @param {string} query
 * @param {number} batchSize
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteQueryStream(connectionID, query, batchSize) {
    return $Call.ByID(503886492, connectionID, query, batchSize);
}

/**
 * ExecuteReadOnlyQuery validates and executes a SELECT-only query with safety controls.
 * @param {string} connectionID
 * @param {string} query
 * @param {number} maxRows
 * @param {time$0.Duration} timeout
 * @returns {$CancellablePromise<$models.ReadOnlyQueryResult | null>}
 */
export function ExecuteReadOnlyQuery(connectionID, query, maxRows, timeout) {
    return $Call.ByID(2691877842, connectionID, query, maxRows, timeout).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ExecuteReadOnlyQueryWithPagination executes a SELECT query with pagination support.
 * @param {string} connectionID
 * @param {string} query
 * @param {number} pageSize
 * @param {number} offset
 * @param {time$0.Duration} timeout
 * @returns {$CancellablePromise<$models.ReadOnlyQueryResult | null>}
 */
export function ExecuteReadOnlyQueryWithPagination(connectionID, query, pageSize, offset, timeout) {
    return $Call.ByID(1781300662, connectionID, query, pageSize, offset, timeout).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ExecuteSyntheticQuery executes a query against synthetic views
 * @param {string} sql
 * @returns {$CancellablePromise<$models.QueryResponse | null>}
 */
export function ExecuteSyntheticQuery(sql) {
    return $Call.ByID(248081289, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ExplainQuery returns query execution plan
 * @param {string} connectionID
 * @param {string} query
 * @returns {$CancellablePromise<string>}
 */
export function ExplainQuery(connectionID, query) {
    return $Call.ByID(2275359984, connectionID, query);
}

/**
 * @returns {$CancellablePromise<{ [_: string]: services$0.KeyboardAction }>}
 */
export function ExportKeyboardBindings() {
    return $Call.ByID(3075456612).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(filePath) {
    return $Call.ByID(2577714203, filePath);
}

/**
 * FinishWebAuthnAuthentication completes the WebAuthn authentication process
 * @param {string} userID
 * @param {string} assertionJSON
 * @returns {$CancellablePromise<string>}
 */
export function FinishWebAuthnAuthentication(userID, assertionJSON) {
    return $Call.ByID(4137881488, userID, assertionJSON);
}

/**
 * FinishWebAuthnRegistration completes the WebAuthn registration process
 * @param {string} userID
 * @param {string} credentialJSON
 * @returns {$CancellablePromise<boolean>}
 */
export function FinishWebAuthnRegistration(userID, credentialJSON) {
    return $Call.ByID(1288062605, userID, credentialJSON);
}

/**
 * FixSQLError attempts to fix a SQL error
 * @param {string} query
 * @param {string} error
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.FixedSQLResponse | null>}
 */
export function FixSQLError(query, error, connectionID) {
    return $Call.ByID(3994346090, query, error, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * FixSQLErrorWithOptions applies AI-based fixes with provider-specific configuration
 * @param {$models.FixSQLRequest} req
 * @returns {$CancellablePromise<$models.FixedSQLResponse | null>}
 */
export function FixSQLErrorWithOptions(req) {
    return $Call.ByID(3861064536, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GenerateMigrationSQL generates SQL statements to migrate from source to target schema
 * @param {string} sourceConnID
 * @param {string} targetConnID
 * @param {boolean} reverse
 * @returns {$CancellablePromise<schemadiff$0.MigrationScript | null>}
 */
export function GenerateMigrationSQL(sourceConnID, targetConnID, reverse) {
    return $Call.ByID(26209926, sourceConnID, targetConnID, reverse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GenerateMigrationSQLFromSnapshot generates SQL to migrate from snapshot to live
 * @param {string} connectionID
 * @param {string} snapshotID
 * @param {boolean} reverse
 * @returns {$CancellablePromise<schemadiff$0.MigrationScript | null>}
 */
export function GenerateMigrationSQLFromSnapshot(connectionID, snapshotID, reverse) {
    return $Call.ByID(2655483150, connectionID, snapshotID, reverse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GenerateSQLFromNaturalLanguage generates SQL from a natural language prompt
 * @param {$models.NLQueryRequest} req
 * @returns {$CancellablePromise<$models.GeneratedSQLResponse | null>}
 */
export function GenerateSQLFromNaturalLanguage(req) {
    return $Call.ByID(2412685321, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GenericChat handles generic conversational AI requests without SQL-specific expectations
 * @param {$models.GenericChatRequest} req
 * @returns {$CancellablePromise<$models.GenericChatResponse | null>}
 */
export function GenericChat(req) {
    return $Call.ByID(4011435820, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetAIConfiguration returns the currently active AI provider configuration with masked secrets.
 * @returns {$CancellablePromise<$models.ProviderConfig>}
 */
export function GetAIConfiguration() {
    return $Call.ByID(75667429).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetAIProviderStatus returns the status of available AI providers
 * @returns {$CancellablePromise<{ [_: string]: $models.ProviderStatus }>}
 */
export function GetAIProviderStatus() {
    return $Call.ByID(4234923394).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: services$0.KeyboardAction }>}
 */
export function GetAllKeyboardBindings() {
    return $Call.ByID(2065191737).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetAppIcon returns the main application icon
 * @returns {$CancellablePromise<string>}
 */
export function GetAppIcon() {
    return $Call.ByID(1367652535).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetAppVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1780012486);
}

/**
 * GetAvailableEnvironments returns all unique environment tags across connections
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableEnvironments() {
    return $Call.ByID(1342220808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetCatalogStats returns statistics about the catalog
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.CatalogStats | null>}
 */
export function GetCatalogStats(connectionID) {
    return $Call.ByID(3308440257, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetColumnCatalogEntry retrieves a column catalog entry
 * @param {string} tableID
 * @param {string} column
 * @returns {$CancellablePromise<catalog$0.ColumnCatalogEntry | null>}
 */
export function GetColumnCatalogEntry(tableID, column) {
    return $Call.ByID(3757670228, tableID, column).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetConnectionCount returns the number of active database connections
 * @returns {$CancellablePromise<number>}
 */
export function GetConnectionCount() {
    return $Call.ByID(3478683838);
}

/**
 * GetConnectionHealth returns health status for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.HealthStatus | null>}
 */
export function GetConnectionHealth(connectionID) {
    return $Call.ByID(1398791729, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetConnectionIDs returns a list of all connection IDs
 * @returns {$CancellablePromise<string[]>}
 */
export function GetConnectionIDs() {
    return $Call.ByID(494301979).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: database$0.PoolStats }>}
 */
export function GetConnectionStats() {
    return $Call.ByID(3005624906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetCurrentVersion returns the current application version
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(1827245900);
}

/**
 * GetDarkIcon returns the dark theme icon
 * @returns {$CancellablePromise<string>}
 */
export function GetDarkIcon() {
    return $Call.ByID(2015355414).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {string} dbType
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetDatabaseTypeInfo(dbType) {
    return $Call.ByID(1900415618, dbType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDatabaseVersion returns the database version
 * @param {string} connectionID
 * @returns {$CancellablePromise<string>}
 */
export function GetDatabaseVersion(connectionID) {
    return $Call.ByID(1255644358, connectionID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsPath() {
    return $Call.ByID(3773782479);
}

/**
 * GetEditableMetadata returns the status of an editable metadata job
 * @param {string} jobID
 * @returns {$CancellablePromise<$models.EditableMetadataJobResponse | null>}
 */
export function GetEditableMetadata(jobID) {
    return $Call.ByID(441846242, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * File Service Methods
 * @param {string} filePath
 * @returns {$CancellablePromise<services$0.FileInfo | null>}
 */
export function GetFileInfo(filePath) {
    return $Call.ByID(2071650585, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetHomePath returns the user's home directory
 * @returns {$CancellablePromise<string>}
 */
export function GetHomePath() {
    return $Call.ByID(3985783027);
}

/**
 * @returns {$CancellablePromise<{ [_: string]: services$0.KeyboardAction[] }>}
 */
export function GetKeyboardBindingsByCategory() {
    return $Call.ByID(3290697753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * GetLightIcon returns the light theme icon
 * @returns {$CancellablePromise<string>}
 */
export function GetLightIcon() {
    return $Call.ByID(2200330756).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetMultiConnectionSchema returns combined schema information for multiple connections
 * @param {string[]} connectionIDs
 * @returns {$CancellablePromise<$models.CombinedSchema | null>}
 */
export function GetMultiConnectionSchema(connectionIDs) {
    return $Call.ByID(72960379, connectionIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * GetOAuthURL generates an OAuth authorization URL for the specified provider
 * @param {string} provider
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetOAuthURL(provider) {
    return $Call.ByID(2340168415, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * GetPassword retrieves a password using the hybrid password manager
 * connectionID is used as the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, will try encrypted DB first, then fall back to keychain
 * Returns an error if the password is not found or cannot be retrieved
 * @param {string} connectionID
 * @param {string} masterKeyBase64
 * @returns {$CancellablePromise<string>}
 */
export function GetPassword(connectionID, masterKeyBase64) {
    return $Call.ByID(2090530822, connectionID, masterKeyBase64);
}

/**
 * GetQuerySuggestions provides autocomplete suggestions for a partial query
 * @param {string} partialQuery
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.Suggestion[]>}
 */
export function GetQuerySuggestions(partialQuery, connectionID) {
    return $Call.ByID(3710115914, partialQuery, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.RecentFile[]>}
 */
export function GetRecentFiles() {
    return $Call.ByID(401165787).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * GetReport loads a full report definition by ID.
 * @param {string} id
 * @returns {$CancellablePromise<storage$0.Report | null>}
 */
export function GetReport(id) {
    return $Call.ByID(1151741137, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * GetSchemaCacheStats returns statistics about the schema cache
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSchemaCacheStats() {
    return $Call.ByID(2422124137).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSchemaSnapshot retrieves a specific snapshot
 * @param {string} snapshotID
 * @returns {$CancellablePromise<schemadiff$0.SchemaSnapshot | null>}
 */
export function GetSchemaSnapshot(snapshotID) {
    return $Call.ByID(2330905476, snapshotID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * GetSchemas returns available schemas for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSchemas(connectionID) {
    return $Call.ByID(3040170137, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetStoredUserInfo retrieves the stored user info for the specified provider
 * @param {string} provider
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetStoredUserInfo(provider) {
    return $Call.ByID(1410749763, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSupportedDatabaseTypes() {
    return $Call.ByID(1433824839).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetSyntheticSchema returns the schema information for synthetic views
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSyntheticSchema() {
    return $Call.ByID(3699596205).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSyntheticView retrieves a synthetic view by ID
 * @param {string} id
 * @returns {$CancellablePromise<storage$0.ViewDefinition | null>}
 */
export function GetSyntheticView(id) {
    return $Call.ByID(1419198795, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * GetTableCatalogEntry retrieves a table catalog entry
 * @param {string} connectionID
 * @param {string} schema
 * @param {string} table
 * @returns {$CancellablePromise<catalog$0.TableCatalogEntry | null>}
 */
export function GetTableCatalogEntry(connectionID, schema, table) {
    return $Call.ByID(629292416, connectionID, schema, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * GetTableStructure returns the structure of a table
 * @param {string} connectionID
 * @param {string} schema
 * @param {string} table
 * @returns {$CancellablePromise<$models.TableStructure | null>}
 */
export function GetTableStructure(connectionID, schema, table) {
    return $Call.ByID(70743122, connectionID, schema, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * GetTables returns tables in a schema
 * @param {string} connectionID
 * @param {string} schema
 * @returns {$CancellablePromise<$models.TableInfo[]>}
 */
export function GetTables(connectionID, schema) {
    return $Call.ByID(3495117462, connectionID, schema).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTempDir() {
    return $Call.ByID(3464696904);
}

/**
 * @param {string} dirPath
 * @param {string[]} extensions
 * @returns {$CancellablePromise<services$0.FileInfo[]>}
 */
export function GetWorkspaceFiles(dirPath, extensions) {
    return $Call.ByID(1084149763, dirPath, extensions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType64($result);
    }));
}

/**
 * Keyboard Service Methods
 * @param {services$0.KeyboardEvent} event
 * @returns {$CancellablePromise<void>}
 */
export function HandleKeyboardEvent(event) {
    return $Call.ByID(1466593614, event);
}

/**
 * HasPassword checks if a password exists in either keychain or encrypted DB
 * Returns true if the password exists, false otherwise
 * @param {string} connectionID
 * @returns {$CancellablePromise<boolean>}
 */
export function HasPassword(connectionID) {
    return $Call.ByID(3923504330, connectionID);
}

/**
 * HasWebAuthnCredential checks if a user has registered WebAuthn credentials
 * @param {string} userID
 * @returns {$CancellablePromise<boolean>}
 */
export function HasWebAuthnCredential(userID) {
    return $Call.ByID(180524956, userID);
}

/**
 * @returns {$CancellablePromise<{ [_: string]: $models.HealthStatus | null }>}
 */
export function HealthCheckAll() {
    return $Call.ByID(3529618192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * @param {{ [_: string]: services$0.KeyboardAction }} bindings
 * @returns {$CancellablePromise<void>}
 */
export function ImportKeyboardBindings(bindings) {
    return $Call.ByID(1481470463, bindings);
}

/**
 * InsertQueryRow inserts a new row via editable metadata guarantees
 * @param {$models.QueryRowInsertRequest} req
 * @returns {$CancellablePromise<$models.QueryRowInsertResponse | null>}
 */
export function InsertQueryRow(req) {
    return $Call.ByID(1258738320, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType67($result);
    }));
}

/**
 * InvalidateAllSchemas invalidates all cached schemas
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateAllSchemas() {
    return $Call.ByID(3942236909);
}

/**
 * InvalidateSchemaCache invalidates the cached schema for a specific connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateSchemaCache(connectionID) {
    return $Call.ByID(2198815463, connectionID);
}

/**
 * ListCatalogTags lists all tags for an organization
 * @param {string | null} orgID
 * @returns {$CancellablePromise<(catalog$0.CatalogTag | null)[]>}
 */
export function ListCatalogTags(orgID) {
    return $Call.ByID(3314583469, orgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType70($result);
    }));
}

/**
 * ListColumnCatalogEntries lists all column entries for a table
 * @param {string} tableID
 * @returns {$CancellablePromise<(catalog$0.ColumnCatalogEntry | null)[]>}
 */
export function ListColumnCatalogEntries(tableID) {
    return $Call.ByID(3925182350, tableID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType71($result);
    }));
}

/**
 * ListConnectionDatabases returns the databases available for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.ListDatabasesResponse | null>}
 */
export function ListConnectionDatabases(connectionID) {
    return $Call.ByID(3887169713, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * ListConnections returns all active connections
 * @returns {$CancellablePromise<string[]>}
 */
export function ListConnections() {
    return $Call.ByID(786053378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListReports returns summaries for all saved reports.
 * @returns {$CancellablePromise<storage$0.ReportSummary[]>}
 */
export function ListReports() {
    return $Call.ByID(3820054524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * ListSchemaSnapshots lists all saved schema snapshots
 * @returns {$CancellablePromise<(schemadiff$0.SnapshotMetadata | null)[]>}
 */
export function ListSchemaSnapshots() {
    return $Call.ByID(2623725391).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType76($result);
    }));
}

/**
 * ListSyntheticViews returns a list of all synthetic views
 * @returns {$CancellablePromise<$models.SyntheticViewSummary[]>}
 */
export function ListSyntheticViews() {
    return $Call.ByID(2188456074).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType78($result);
    }));
}

/**
 * ListTableCatalogEntries lists all table entries for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<(catalog$0.TableCatalogEntry | null)[]>}
 */
export function ListTableCatalogEntries(connectionID) {
    return $Call.ByID(1323762206, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType79($result);
    }));
}

/**
 * LoadAIMemorySessions retrieves previously stored AI memory sessions
 * @returns {$CancellablePromise<$models.AIMemorySessionPayload[]>}
 */
export function LoadAIMemorySessions() {
    return $Call.ByID(3236301305).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType81($result);
    }));
}

/**
 * Logout removes the stored token for the specified provider
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function Logout(provider) {
    return $Call.ByID(1110373539, provider);
}

/**
 * MarkColumnAsPII marks a column as containing PII
 * @param {string} tableID
 * @param {string} columnName
 * @param {string} piiType
 * @param {number} confidence
 * @returns {$CancellablePromise<void>}
 */
export function MarkColumnAsPII(tableID, columnName, piiType, confidence) {
    return $Call.ByID(821878624, tableID, columnName, piiType, confidence);
}

/**
 * OnShutdown is called when the app is shutting down
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(999779538);
}

/**
 * OnStartup is called when the app starts, before the frontend is loaded
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup() {
    return $Call.ByID(2232168041);
}

/**
 * OnUrlOpen handles custom protocol URL callbacks (e.g., OAuth redirects)
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OnUrlOpen(url) {
    return $Call.ByID(3622503861, url);
}

/**
 * OpenDownloadPage opens the download page in the default browser
 * @returns {$CancellablePromise<void>}
 */
export function OpenDownloadPage() {
    return $Call.ByID(1161524398);
}

/**
 * OpenFileDialog opens a file dialog and returns the selected file path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog() {
    return $Call.ByID(4196526771);
}

/**
 * OptimizeQuery optimizes a SQL query
 * @param {string} query
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.OptimizationResponse | null>}
 */
export function OptimizeQuery(query, connectionID) {
    return $Call.ByID(1672334634, query, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType83($result);
    }));
}

/**
 * ParseQueryConnections extracts connection IDs from a query without validating
 * @param {string} query
 * @returns {$CancellablePromise<string[]>}
 */
export function ParseQueryConnections(query) {
    return $Call.ByID(2437565073, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ReadFile reads a file and returns its content
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(filePath) {
    return $Call.ByID(1160596971, filePath);
}

/**
 * RecallAIMemorySessions returns the most relevant stored memories for the given prompt
 * @param {string} prompt
 * @param {number} limit
 * @returns {$CancellablePromise<$models.AIMemoryRecallResult[]>}
 */
export function RecallAIMemorySessions(prompt, limit) {
    return $Call.ByID(4253601536, prompt, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType85($result);
    }));
}

/**
 * RefreshSchema forces a refresh of the schema for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function RefreshSchema(connectionID) {
    return $Call.ByID(2678621399, connectionID);
}

/**
 * RemoveConnection removes a database connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnection(connectionID) {
    return $Call.ByID(3294149945, connectionID);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromRecentFiles(filePath) {
    return $Call.ByID(1094128833, filePath);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function RemoveKeyboardBinding(key) {
    return $Call.ByID(1561873133, key);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetKeyboardBindings() {
    return $Call.ByID(1856288931);
}

/**
 * RunReport executes all (or selected) components within a report.
 * @param {services$0.ReportRunRequest} req
 * @returns {$CancellablePromise<services$0.ReportRunResponse | null>}
 */
export function RunReport(req) {
    return $Call.ByID(547759432, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType87($result);
    }));
}

/**
 * SQLiteDeleteConnection removes a connection from SQLite by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteDeleteConnection(id) {
    return $Call.ByID(1933734182, id);
}

/**
 * SQLiteDeleteQuery removes a saved query from SQLite by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteDeleteQuery(id) {
    return $Call.ByID(2953791022, id);
}

/**
 * SQLiteGetConnection returns a single connection by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.SQLiteConnection | null>}
 */
export function SQLiteGetConnection(id) {
    return $Call.ByID(2554615847, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType89($result);
    }));
}

/**
 * SQLiteGetConnections returns all connections from SQLite
 * @returns {$CancellablePromise<$models.SQLiteConnection[]>}
 */
export function SQLiteGetConnections() {
    return $Call.ByID(127339580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType90($result);
    }));
}

/**
 * SQLiteGetQueries returns all saved queries from SQLite
 * @returns {$CancellablePromise<$models.SQLiteSavedQuery[]>}
 */
export function SQLiteGetQueries() {
    return $Call.ByID(2756490953).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType92($result);
    }));
}

/**
 * SQLiteGetQuery returns a single query by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.SQLiteSavedQuery | null>}
 */
export function SQLiteGetQuery(id) {
    return $Call.ByID(2790040149, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType93($result);
    }));
}

/**
 * SQLiteGetQueryHistory returns query history from SQLite
 * @param {string} connectionID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SQLiteQueryHistory[]>}
 */
export function SQLiteGetQueryHistory(connectionID, limit) {
    return $Call.ByID(1054574639, connectionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType95($result);
    }));
}

/**
 * SQLiteGetSetting retrieves a setting from SQLite
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function SQLiteGetSetting(key) {
    return $Call.ByID(2292519269, key);
}

/**
 * SQLiteSaveConnection saves or updates a connection in SQLite
 * Accepts JSON string and parses it into storage.Connection
 * @param {string} connectionJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveConnection(connectionJSON) {
    return $Call.ByID(3746072808, connectionJSON);
}

/**
 * SQLiteSaveQuery saves or updates a query in SQLite
 * Accepts JSON string and parses it into storage.SavedQuery
 * @param {string} queryJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveQuery(queryJSON) {
    return $Call.ByID(4141646484, queryJSON);
}

/**
 * SQLiteSaveQueryHistory saves a query history entry to SQLite
 * Accepts JSON string and parses it into storage.QueryHistory
 * @param {string} historyJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveQueryHistory(historyJSON) {
    return $Call.ByID(1657419188, historyJSON);
}

/**
 * SQLiteSetSetting saves a setting to SQLite
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSetSetting(key, value) {
    return $Call.ByID(2163790673, key, value);
}

/**
 * SaveAIMemorySessions persists AI memory sessions and indexes them for recall
 * @param {$models.AIMemorySessionPayload[]} sessions
 * @returns {$CancellablePromise<void>}
 */
export function SaveAIMemorySessions(sessions) {
    return $Call.ByID(1993991416, sessions);
}

/**
 * SaveConnection saves connection metadata to storage
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveConnection(req) {
    return $Call.ByID(865625064, req);
}

/**
 * SaveFileDialog opens a save file dialog and returns the selected file path
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog() {
    return $Call.ByID(1166008166);
}

/**
 * SaveReport creates or updates a report definition.
 * @param {storage$0.Report} report
 * @returns {$CancellablePromise<storage$0.Report | null>}
 */
export function SaveReport(report) {
    return $Call.ByID(358675690, report).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * SaveSyntheticView saves a synthetic view definition
 * @param {storage$0.ViewDefinition} viewDef
 * @returns {$CancellablePromise<string>}
 */
export function SaveSyntheticView(viewDef) {
    return $Call.ByID(1583757022, viewDef);
}

/**
 * @param {string} filename
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveToDownloads(filename, content) {
    return $Call.ByID(1947379714, filename, content);
}

/**
 * SearchCatalog searches the catalog for tables and columns
 * @param {string} query
 * @param {catalog$0.SearchFilters | null} filters
 * @returns {$CancellablePromise<catalog$0.SearchResults | null>}
 */
export function SearchCatalog(query, filters) {
    return $Call.ByID(36373548, query, filters).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType97($result);
    }));
}

/**
 * SetApplication stores the v3 application reference for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * SetMainWindow stores the main window reference for dialogs
 * @param {application$0.Window} window
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(window) {
    return $Call.ByID(843697430, window);
}

/**
 * ShowErrorDialog shows an error dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowErrorDialog(title, message) {
    return $Call.ByID(2999711890, title, message);
}

/**
 * ShowInfoDialog shows an information dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowInfoDialog(title, message) {
    return $Call.ByID(1979499672, title, message);
}

/**
 * ShowNotification shows a notification using Wails MessageDialog
 * @param {string} title
 * @param {string} message
 * @param {boolean} isError
 * @returns {$CancellablePromise<void>}
 */
export function ShowNotification(title, message, isError) {
    return $Call.ByID(3229613467, title, message, isError);
}

/**
 * ShowQuestionDialog shows a question dialog and returns the result
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<boolean>}
 */
export function ShowQuestionDialog(title, message) {
    return $Call.ByID(3506982520, title, message);
}

/**
 * StartClaudeCodeLogin begins the Claude CLI login flow.
 * @param {string} binaryPath
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function StartClaudeCodeLogin(binaryPath) {
    return $Call.ByID(2387309081, binaryPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * StartCodexLogin begins the OpenAI CLI login flow for Codex access.
 * @param {string} binaryPath
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function StartCodexLogin(binaryPath) {
    return $Call.ByID(2615209343, binaryPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * StartWebAuthnAuthentication initiates the WebAuthn authentication process
 * @param {string} userID
 * @returns {$CancellablePromise<string>}
 */
export function StartWebAuthnAuthentication(userID) {
    return $Call.ByID(3560959625, userID);
}

/**
 * StartWebAuthnRegistration initiates the WebAuthn registration process
 * @param {string} userID
 * @param {string} userName
 * @returns {$CancellablePromise<string>}
 */
export function StartWebAuthnRegistration(userID, userName) {
    return $Call.ByID(651240800, userID, userName);
}

/**
 * StorageCompleteMigration marks the IndexedDB to SQLite migration as complete
 * @returns {$CancellablePromise<void>}
 */
export function StorageCompleteMigration() {
    return $Call.ByID(3959048667);
}

/**
 * StorageImportConnections imports connections from IndexedDB format to SQLite
 * @param {string} connectionsJSON
 * @returns {$CancellablePromise<services$0.ImportConnectionsResult | null>}
 */
export function StorageImportConnections(connectionsJSON) {
    return $Call.ByID(3271942400, connectionsJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType101($result);
    }));
}

/**
 * StorageImportHistory imports query history from IndexedDB format to SQLite
 * @param {string} historyJSON
 * @returns {$CancellablePromise<services$0.ImportHistoryResult | null>}
 */
export function StorageImportHistory(historyJSON) {
    return $Call.ByID(3263065309, historyJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType103($result);
    }));
}

/**
 * StorageImportPreferences imports preferences from IndexedDB format to SQLite
 * @param {string} preferencesJSON
 * @returns {$CancellablePromise<void>}
 */
export function StorageImportPreferences(preferencesJSON) {
    return $Call.ByID(3052730095, preferencesJSON);
}

/**
 * StorageImportQueries imports saved queries from IndexedDB format to SQLite
 * @param {string} queriesJSON
 * @returns {$CancellablePromise<services$0.ImportQueriesResult | null>}
 */
export function StorageImportQueries(queriesJSON) {
    return $Call.ByID(3687129421, queriesJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType105($result);
    }));
}

/**
 * StorageMigrationStatus returns the current migration status
 * @returns {$CancellablePromise<services$0.MigrationStatus | null>}
 */
export function StorageMigrationStatus() {
    return $Call.ByID(1353832560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType107($result);
    }));
}

/**
 * StorePassword stores a password securely using the hybrid password manager
 * connectionID is used as the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, uses keychain only (graceful degradation)
 * @param {string} connectionID
 * @param {string} password
 * @param {string} masterKeyBase64
 * @returns {$CancellablePromise<void>}
 */
export function StorePassword(connectionID, password, masterKeyBase64) {
    return $Call.ByID(318532779, connectionID, password, masterKeyBase64);
}

/**
 * StreamAIQueryAgent coordinates a multi-agent workflow to satisfy a user query.
 * @param {$models.AIQueryAgentRequest} req
 * @returns {$CancellablePromise<$models.AIQueryAgentResponse | null>}
 */
export function StreamAIQueryAgent(req) {
    return $Call.ByID(2336668206, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType109($result);
    }));
}

/**
 * SuggestVisualization suggests appropriate visualizations for query results
 * @param {$models.ResultData} resultData
 * @returns {$CancellablePromise<$models.VizSuggestion | null>}
 */
export function SuggestVisualization(resultData) {
    return $Call.ByID(1404223111, resultData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType111($result);
    }));
}

/**
 * SwitchConnectionDatabase switches the active database for a connection
 * @param {$models.SwitchDatabaseRequest} req
 * @returns {$CancellablePromise<$models.SwitchDatabaseResponse | null>}
 */
export function SwitchConnectionDatabase(req) {
    return $Call.ByID(1352524616, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType113($result);
    }));
}

/**
 * SyncCatalogFromConnection syncs the catalog with the actual database schema
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.CatalogSyncResult | null>}
 */
export function SyncCatalogFromConnection(connectionID) {
    return $Call.ByID(531478245, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType115($result);
    }));
}

/**
 * TestAIProvider tests a provider configuration without saving it
 * @param {$models.ProviderConfig} config
 * @returns {$CancellablePromise<$models.ProviderStatus | null>}
 */
export function TestAIProvider(config) {
    return $Call.ByID(3088725798, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType116($result);
    }));
}

/**
 * TestAnthropicConnection tests Anthropic provider connection
 * @param {string} apiKey
 * @param {string} model
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestAnthropicConnection(apiKey, model) {
    return $Call.ByID(2386128411, apiKey, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * TestClaudeCodeConnection tests Claude Code provider connection
 * @param {string} binaryPath
 * @param {string} model
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestClaudeCodeConnection(binaryPath, model) {
    return $Call.ByID(3051505850, binaryPath, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * TestCodexConnection tests Codex provider connection
 * @param {string} apiKey
 * @param {string} model
 * @param {string} organization
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestCodexConnection(apiKey, model, organization) {
    return $Call.ByID(2061763052, apiKey, model, organization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * TestConnection tests a database connection without creating it
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(req) {
    return $Call.ByID(1257240193, req);
}

/**
 * TestHuggingFaceConnection tests HuggingFace provider connection
 * @param {string} endpoint
 * @param {string} model
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestHuggingFaceConnection(endpoint, model) {
    return $Call.ByID(2660983305, endpoint, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * TestOllamaConnection tests Ollama provider connection
 * @param {string} endpoint
 * @param {string} model
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestOllamaConnection(endpoint, model) {
    return $Call.ByID(2440689243, endpoint, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * TestOpenAIConnection tests OpenAI provider connection
 * @param {string} apiKey
 * @param {string} model
 * @returns {$CancellablePromise<$models.AITestResponse | null>}
 */
export function TestOpenAIConnection(apiKey, model) {
    return $Call.ByID(3093951147, apiKey, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType99($result);
    }));
}

/**
 * UpdateColumnCatalogEntry updates a column catalog entry
 * @param {catalog$0.ColumnCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function UpdateColumnCatalogEntry(entry) {
    return $Call.ByID(3476259923, entry);
}

/**
 * UpdateQueryRow persists edits made to a query result row
 * @param {$models.QueryRowUpdateRequest} req
 * @returns {$CancellablePromise<$models.QueryRowUpdateResponse | null>}
 */
export function UpdateQueryRow(req) {
    return $Call.ByID(712473884, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType118($result);
    }));
}

/**
 * UpdateTableCatalogEntry updates a table catalog entry
 * @param {catalog$0.TableCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTableCatalogEntry(entry) {
    return $Call.ByID(3508883577, entry);
}

/**
 * ValidateMultiQuery validates a multi-database query without executing it
 * @param {string} query
 * @returns {$CancellablePromise<$models.ValidationResult | null>}
 */
export function ValidateMultiQuery(query) {
    return $Call.ByID(2326210384, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType120($result);
    }));
}

/**
 * WriteFile writes content to a file
 * @param {string} filePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(filePath, content) {
    return $Call.ByID(3562730546, filePath, content);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = schemadiff$0.SchemaDiff.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.ConnectionInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = schemadiff$0.SnapshotMetadata.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.QueryRowDeleteResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.MultiQueryResponse.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.QueryResponse.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.ReadOnlyQueryResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = services$0.KeyboardAction.createFrom;
const $$createType18 = $Create.Map($Create.Any, $$createType17);
const $$createType19 = $models.FixedSQLResponse.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = schemadiff$0.MigrationScript.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.GeneratedSQLResponse.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $models.GenericChatResponse.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $models.ProviderConfig.createFrom;
const $$createType28 = $models.ProviderStatus.createFrom;
const $$createType29 = $Create.Map($Create.Any, $$createType28);
const $$createType30 = $Create.Array($Create.Any);
const $$createType31 = $models.CatalogStats.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = catalog$0.ColumnCatalogEntry.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = $models.HealthStatus.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = database$0.PoolStats.createFrom;
const $$createType38 = $Create.Map($Create.Any, $$createType37);
const $$createType39 = $models.EditableMetadataJobResponse.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = services$0.FileInfo.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = $Create.Array($$createType17);
const $$createType44 = $Create.Map($Create.Any, $$createType43);
const $$createType45 = $models.CombinedSchema.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = $Create.Map($Create.Any, $Create.Any);
const $$createType48 = $models.Suggestion.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = services$0.RecentFile.createFrom;
const $$createType51 = $Create.Array($$createType50);
const $$createType52 = storage$0.Report.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = schemadiff$0.SchemaSnapshot.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = storage$0.ViewDefinition.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = catalog$0.TableCatalogEntry.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = $models.TableStructure.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = $models.TableInfo.createFrom;
const $$createType63 = $Create.Array($$createType62);
const $$createType64 = $Create.Array($$createType41);
const $$createType65 = $Create.Map($Create.Any, $$createType36);
const $$createType66 = $models.QueryRowInsertResponse.createFrom;
const $$createType67 = $Create.Nullable($$createType66);
const $$createType68 = catalog$0.CatalogTag.createFrom;
const $$createType69 = $Create.Nullable($$createType68);
const $$createType70 = $Create.Array($$createType69);
const $$createType71 = $Create.Array($$createType34);
const $$createType72 = $models.ListDatabasesResponse.createFrom;
const $$createType73 = $Create.Nullable($$createType72);
const $$createType74 = storage$0.ReportSummary.createFrom;
const $$createType75 = $Create.Array($$createType74);
const $$createType76 = $Create.Array($$createType8);
const $$createType77 = $models.SyntheticViewSummary.createFrom;
const $$createType78 = $Create.Array($$createType77);
const $$createType79 = $Create.Array($$createType59);
const $$createType80 = $models.AIMemorySessionPayload.createFrom;
const $$createType81 = $Create.Array($$createType80);
const $$createType82 = $models.OptimizationResponse.createFrom;
const $$createType83 = $Create.Nullable($$createType82);
const $$createType84 = $models.AIMemoryRecallResult.createFrom;
const $$createType85 = $Create.Array($$createType84);
const $$createType86 = services$0.ReportRunResponse.createFrom;
const $$createType87 = $Create.Nullable($$createType86);
const $$createType88 = $models.SQLiteConnection.createFrom;
const $$createType89 = $Create.Nullable($$createType88);
const $$createType90 = $Create.Array($$createType88);
const $$createType91 = $models.SQLiteSavedQuery.createFrom;
const $$createType92 = $Create.Array($$createType91);
const $$createType93 = $Create.Nullable($$createType91);
const $$createType94 = $models.SQLiteQueryHistory.createFrom;
const $$createType95 = $Create.Array($$createType94);
const $$createType96 = catalog$0.SearchResults.createFrom;
const $$createType97 = $Create.Nullable($$createType96);
const $$createType98 = $models.AITestResponse.createFrom;
const $$createType99 = $Create.Nullable($$createType98);
const $$createType100 = services$0.ImportConnectionsResult.createFrom;
const $$createType101 = $Create.Nullable($$createType100);
const $$createType102 = services$0.ImportHistoryResult.createFrom;
const $$createType103 = $Create.Nullable($$createType102);
const $$createType104 = services$0.ImportQueriesResult.createFrom;
const $$createType105 = $Create.Nullable($$createType104);
const $$createType106 = services$0.MigrationStatus.createFrom;
const $$createType107 = $Create.Nullable($$createType106);
const $$createType108 = $models.AIQueryAgentResponse.createFrom;
const $$createType109 = $Create.Nullable($$createType108);
const $$createType110 = $models.VizSuggestion.createFrom;
const $$createType111 = $Create.Nullable($$createType110);
const $$createType112 = $models.SwitchDatabaseResponse.createFrom;
const $$createType113 = $Create.Nullable($$createType112);
const $$createType114 = $models.CatalogSyncResult.createFrom;
const $$createType115 = $Create.Nullable($$createType114);
const $$createType116 = $Create.Nullable($$createType28);
const $$createType117 = $models.QueryRowUpdateResponse.createFrom;
const $$createType118 = $Create.Nullable($$createType117);
const $$createType119 = $models.ValidationResult.createFrom;
const $$createType120 = $Create.Nullable($$createType119);
