// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogService handles data catalog operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "./pkg/catalog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssignTableSteward assigns a steward to a table
 */
export function AssignTableSteward(tableID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(2871533907, tableID, userID);
}

/**
 * CreateCatalogTag creates a new custom tag
 */
export function CreateCatalogTag(tag: catalog$0.CatalogTag | null): $CancellablePromise<void> {
    return $Call.ByID(1831868915, tag);
}

/**
 * CreateColumnCatalogEntry creates a new column catalog entry
 */
export function CreateColumnCatalogEntry(entry: catalog$0.ColumnCatalogEntry | null): $CancellablePromise<void> {
    return $Call.ByID(3516402597, entry);
}

/**
 * CreateTableCatalogEntry creates a new table entry in the catalog
 */
export function CreateTableCatalogEntry(entry: catalog$0.TableCatalogEntry | null): $CancellablePromise<void> {
    return $Call.ByID(2199815167, entry);
}

/**
 * DeleteCatalogTag deletes a custom tag
 */
export function DeleteCatalogTag(id: string): $CancellablePromise<void> {
    return $Call.ByID(3990439336, id);
}

/**
 * DeleteTableCatalogEntry deletes a table catalog entry
 */
export function DeleteTableCatalogEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(1778001386, id);
}

/**
 * GetCatalogStats returns statistics about the catalog
 */
export function GetCatalogStats(connectionID: string): $CancellablePromise<$models.CatalogStats | null> {
    return $Call.ByID(3547469908, connectionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetColumnCatalogEntry retrieves a column catalog entry
 */
export function GetColumnCatalogEntry(tableID: string, column: string): $CancellablePromise<catalog$0.ColumnCatalogEntry | null> {
    return $Call.ByID(3226829965, tableID, column).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTableCatalogEntry retrieves a table catalog entry
 */
export function GetTableCatalogEntry(connectionID: string, schema: string, table: string): $CancellablePromise<catalog$0.TableCatalogEntry | null> {
    return $Call.ByID(3260243399, connectionID, schema, table).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListCatalogTags lists all tags for an organization
 */
export function ListCatalogTags(orgID: string | null): $CancellablePromise<(catalog$0.CatalogTag | null)[]> {
    return $Call.ByID(2920466552, orgID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListColumnCatalogEntries lists all column entries for a table
 */
export function ListColumnCatalogEntries(tableID: string): $CancellablePromise<(catalog$0.ColumnCatalogEntry | null)[]> {
    return $Call.ByID(3259698657, tableID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListTableCatalogEntries lists all table entries for a connection
 */
export function ListTableCatalogEntries(connectionID: string): $CancellablePromise<(catalog$0.TableCatalogEntry | null)[]> {
    return $Call.ByID(1487031295, connectionID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * MarkColumnAsPII marks a column as containing PII
 */
export function MarkColumnAsPII(tableID: string, columnName: string, piiType: string, confidence: number): $CancellablePromise<void> {
    return $Call.ByID(2762590261, tableID, columnName, piiType, confidence);
}

/**
 * SearchCatalog searches the catalog for tables and columns
 */
export function SearchCatalog(query: string, filters: catalog$0.SearchFilters | null): $CancellablePromise<catalog$0.SearchResults | null> {
    return $Call.ByID(461360161, query, filters).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SyncCatalogFromConnection syncs the catalog with the actual database schema
 */
export function SyncCatalogFromConnection(connectionID: string): $CancellablePromise<$models.CatalogSyncResult | null> {
    return $Call.ByID(2244516948, connectionID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * UpdateColumnCatalogEntry updates a column catalog entry
 */
export function UpdateColumnCatalogEntry(entry: catalog$0.ColumnCatalogEntry | null): $CancellablePromise<void> {
    return $Call.ByID(3880007192, entry);
}

/**
 * UpdateTableCatalogEntry updates a table catalog entry
 */
export function UpdateTableCatalogEntry(entry: catalog$0.TableCatalogEntry | null): $CancellablePromise<void> {
    return $Call.ByID(3506534348, entry);
}

// Private type creation functions
const $$createType0 = $models.CatalogStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = catalog$0.ColumnCatalogEntry.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = catalog$0.TableCatalogEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = catalog$0.CatalogTag.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType3);
const $$createType10 = $Create.Array($$createType5);
const $$createType11 = catalog$0.SearchResults.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.CatalogSyncResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
