// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService handles all database connection operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./pkg/database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConnection creates a new database connection
 */
export function CreateConnection(req: $models.ConnectionRequest): $CancellablePromise<$models.ConnectionInfo | null> {
    return $Call.ByID(3604157573, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAvailableEnvironments returns all unique environment tags across connections
 */
export function GetAvailableEnvironments(): $CancellablePromise<string[]> {
    return $Call.ByID(71285460).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetConnectionCount returns the number of active database connections
 */
export function GetConnectionCount(): $CancellablePromise<number> {
    return $Call.ByID(1410668602);
}

/**
 * GetConnectionHealth returns the health status of a connection
 */
export function GetConnectionHealth(connectionID: string): $CancellablePromise<$models.HealthStatus | null> {
    return $Call.ByID(1803982829, connectionID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConnectionIDs returns a list of all connection IDs
 */
export function GetConnectionIDs(): $CancellablePromise<string[]> {
    return $Call.ByID(2806462223).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetConnectionStats returns connection pool statistics
 */
export function GetConnectionStats(): $CancellablePromise<{ [_ in string]?: database$0.PoolStats }> {
    return $Call.ByID(114194806).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDatabaseTypeInfo returns information about a database type
 */
export function GetDatabaseTypeInfo(dbType: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2893133902, dbType).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetDatabaseVersion returns the database version
 */
export function GetDatabaseVersion(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(2776337458, connectionID);
}

/**
 * GetSchemaCacheStats returns statistics about the schema cache
 */
export function GetSchemaCacheStats(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1242619645).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSupportedDatabaseTypes returns supported database types
 */
export function GetSupportedDatabaseTypes(): $CancellablePromise<string[]> {
    return $Call.ByID(3162222467).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * HealthCheckAll performs health checks on all connections
 */
export function HealthCheckAll(): $CancellablePromise<{ [_ in string]?: $models.HealthStatus | null }> {
    return $Call.ByID(1444971836).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * InvalidateAllSchemas invalidates all cached schemas
 */
export function InvalidateAllSchemas(): $CancellablePromise<void> {
    return $Call.ByID(323309817);
}

/**
 * InvalidateSchemaCache invalidates the cached schema for a specific connection
 */
export function InvalidateSchemaCache(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3216727651, connectionID);
}

/**
 * ListConnectionDatabases returns the databases available for a connection
 */
export function ListConnectionDatabases(connectionID: string): $CancellablePromise<$models.ListDatabasesResponse | null> {
    return $Call.ByID(4250284325, connectionID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListConnections returns all active connections
 */
export function ListConnections(): $CancellablePromise<string[]> {
    return $Call.ByID(645322174).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RefreshSchema forces a refresh of the schema for a connection
 */
export function RefreshSchema(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2911579779, connectionID);
}

/**
 * RemoveConnection removes a database connection
 */
export function RemoveConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2397696645, connectionID);
}

/**
 * SaveConnection saves connection metadata
 */
export function SaveConnection(req: $models.ConnectionRequest): $CancellablePromise<void> {
    return $Call.ByID(99910012, req);
}

/**
 * SwitchConnectionDatabase switches the active database for a connection
 */
export function SwitchConnectionDatabase(req: $models.SwitchDatabaseRequest): $CancellablePromise<$models.SwitchDatabaseResponse | null> {
    return $Call.ByID(2707454740, req).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * TestConnection tests a database connection
 */
export function TestConnection(req: $models.ConnectionRequest): $CancellablePromise<void> {
    return $Call.ByID(854926829, req);
}

// Private type creation functions
const $$createType0 = $models.ConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.HealthStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = database$0.PoolStats.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Map($Create.Any, $$createType4);
const $$createType9 = $models.ListDatabasesResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.SwitchDatabaseResponse.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
