// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaDiffService handles schema comparison operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemadiff$0 from "./pkg/schemadiff/models.js";

/**
 * CompareConnectionSchemas compares schemas between two database connections
 */
export function CompareConnectionSchemas(sourceConnID: string, targetConnID: string): $CancellablePromise<schemadiff$0.SchemaDiff | null> {
    return $Call.ByID(3071697380, sourceConnID, targetConnID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CompareWithSnapshot compares a live connection against a saved snapshot
 */
export function CompareWithSnapshot(connectionID: string, snapshotID: string): $CancellablePromise<schemadiff$0.SchemaDiff | null> {
    return $Call.ByID(1353733224, connectionID, snapshotID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateSchemaSnapshot creates a point-in-time snapshot of a database schema
 */
export function CreateSchemaSnapshot(connectionID: string, name: string): $CancellablePromise<schemadiff$0.SnapshotMetadata | null> {
    return $Call.ByID(3122713842, connectionID, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeleteSchemaSnapshot deletes a saved snapshot
 */
export function DeleteSchemaSnapshot(snapshotID: string): $CancellablePromise<void> {
    return $Call.ByID(456902973, snapshotID);
}

/**
 * GenerateMigrationSQL generates SQL statements to migrate from source to target schema
 */
export function GenerateMigrationSQL(sourceConnID: string, targetConnID: string, reverse: boolean): $CancellablePromise<schemadiff$0.MigrationScript | null> {
    return $Call.ByID(3218673422, sourceConnID, targetConnID, reverse).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GenerateMigrationSQLFromSnapshot generates SQL to migrate from snapshot to live
 */
export function GenerateMigrationSQLFromSnapshot(connectionID: string, snapshotID: string, reverse: boolean): $CancellablePromise<schemadiff$0.MigrationScript | null> {
    return $Call.ByID(2511041734, connectionID, snapshotID, reverse).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSchemaSnapshot retrieves a specific snapshot
 */
export function GetSchemaSnapshot(snapshotID: string): $CancellablePromise<schemadiff$0.SchemaSnapshot | null> {
    return $Call.ByID(4186385020, snapshotID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListSchemaSnapshots lists all saved schema snapshots
 */
export function ListSchemaSnapshots(): $CancellablePromise<(schemadiff$0.SnapshotMetadata | null)[]> {
    return $Call.ByID(2473637479).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = schemadiff$0.SchemaDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = schemadiff$0.SnapshotMetadata.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = schemadiff$0.MigrationScript.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = schemadiff$0.SchemaSnapshot.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType3);
