// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService handles storage, migration, and synthetic view operations for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSyntheticView deletes a synthetic view by ID
 */
export function DeleteSyntheticView(id: string): $CancellablePromise<void> {
    return $Call.ByID(3854916243, id);
}

/**
 * ExecuteSyntheticQuery executes a query against synthetic views
 */
export function ExecuteSyntheticQuery(sql: string): $CancellablePromise<$models.QueryResponse | null> {
    return $Call.ByID(2835164346, sql).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSyntheticSchema returns the schema information for synthetic views
 */
export function GetSyntheticSchema(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2225737572).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSyntheticView retrieves a synthetic view by ID
 */
export function GetSyntheticView(id: string): $CancellablePromise<storage$0.ViewDefinition | null> {
    return $Call.ByID(3497019894, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListSyntheticViews returns a list of all synthetic views
 */
export function ListSyntheticViews(): $CancellablePromise<$models.SyntheticViewSummary[]> {
    return $Call.ByID(529100323).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SQLiteDeleteConnection removes a connection from SQLite by ID
 */
export function SQLiteDeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3302380827, id);
}

/**
 * SQLiteDeleteQuery removes a saved query from SQLite by ID
 */
export function SQLiteDeleteQuery(id: string): $CancellablePromise<void> {
    return $Call.ByID(1652548153, id);
}

/**
 * SQLiteGetConnection returns a single connection by ID
 */
export function SQLiteGetConnection(id: string): $CancellablePromise<$models.SQLiteConnection | null> {
    return $Call.ByID(103740828, id).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SQLiteGetConnections returns all connections from SQLite
 */
export function SQLiteGetConnections(): $CancellablePromise<$models.SQLiteConnection[]> {
    return $Call.ByID(2867668797).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SQLiteGetQueries returns all saved queries from SQLite
 */
export function SQLiteGetQueries(): $CancellablePromise<$models.SQLiteSavedQuery[]> {
    return $Call.ByID(39574780).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SQLiteGetQuery returns a single query by ID
 */
export function SQLiteGetQuery(id: string): $CancellablePromise<$models.SQLiteSavedQuery | null> {
    return $Call.ByID(3516847336, id).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SQLiteGetQueryHistory returns query history from SQLite
 */
export function SQLiteGetQueryHistory(connectionID: string, limit: number): $CancellablePromise<$models.SQLiteQueryHistory[]> {
    return $Call.ByID(444816272, connectionID, limit).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SQLiteGetSetting retrieves a setting from SQLite
 */
export function SQLiteGetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(1855310904, key);
}

/**
 * SQLiteSaveConnection saves or updates a connection in SQLite
 * Accepts JSON string and parses it into storage.Connection
 */
export function SQLiteSaveConnection(connectionJSON: string): $CancellablePromise<void> {
    return $Call.ByID(371378017, connectionJSON);
}

/**
 * SQLiteSaveQuery saves or updates a query in SQLite
 * Accepts JSON string and parses it into storage.SavedQuery
 */
export function SQLiteSaveQuery(queryJSON: string): $CancellablePromise<void> {
    return $Call.ByID(1433853547, queryJSON);
}

/**
 * SQLiteSaveQueryHistory saves a query history entry to SQLite
 * Accepts JSON string and parses it into storage.QueryHistory
 */
export function SQLiteSaveQueryHistory(historyJSON: string): $CancellablePromise<void> {
    return $Call.ByID(4009481397, historyJSON);
}

/**
 * SQLiteSetSetting saves a setting to SQLite
 */
export function SQLiteSetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3644616044, key, value);
}

/**
 * SaveSyntheticView creates or updates a synthetic view definition
 */
export function SaveSyntheticView(viewDef: storage$0.ViewDefinition): $CancellablePromise<string> {
    return $Call.ByID(357791725, viewDef);
}

/**
 * StorageCompleteMigration marks the IndexedDB to SQLite migration as complete
 */
export function StorageCompleteMigration(): $CancellablePromise<void> {
    return $Call.ByID(3205473058);
}

/**
 * StorageImportConnections imports connections from IndexedDB format to SQLite
 */
export function StorageImportConnections(connectionsJSON: string): $CancellablePromise<services$0.ImportConnectionsResult | null> {
    return $Call.ByID(2361615749, connectionsJSON).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * StorageImportHistory imports query history from IndexedDB format to SQLite
 */
export function StorageImportHistory(historyJSON: string): $CancellablePromise<services$0.ImportHistoryResult | null> {
    return $Call.ByID(3310725060, historyJSON).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * StorageImportPreferences imports preferences from IndexedDB format to SQLite
 */
export function StorageImportPreferences(preferencesJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3048605542, preferencesJSON);
}

/**
 * StorageImportQueries imports saved queries from IndexedDB format to SQLite
 */
export function StorageImportQueries(queriesJSON: string): $CancellablePromise<services$0.ImportQueriesResult | null> {
    return $Call.ByID(3231970420, queriesJSON).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * StorageMigrationStatus returns the current migration status
 */
export function StorageMigrationStatus(): $CancellablePromise<services$0.MigrationStatus | null> {
    return $Call.ByID(1942536077).then(($result: any) => {
        return $$createType22($result);
    });
}

// Private type creation functions
const $$createType0 = $models.QueryResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = storage$0.ViewDefinition.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.SyntheticViewSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.SQLiteConnection.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType7);
const $$createType10 = $models.SQLiteSavedQuery.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Nullable($$createType10);
const $$createType13 = $models.SQLiteQueryHistory.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = services$0.ImportConnectionsResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = services$0.ImportHistoryResult.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = services$0.ImportQueriesResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = services$0.MigrationStatus.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
