// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsKeyboardService handles keyboard-related operations for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * AddKeyboardBinding adds a new keyboard binding
 */
export function AddKeyboardBinding(key: string, action: services$0.KeyboardAction): $CancellablePromise<void> {
    return $Call.ByID(2587193697, key, action);
}

/**
 * ExportKeyboardBindings exports all keyboard bindings
 */
export function ExportKeyboardBindings(): $CancellablePromise<{ [_ in string]?: services$0.KeyboardAction }> {
    return $Call.ByID(244471435).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAllKeyboardBindings returns all keyboard bindings
 */
export function GetAllKeyboardBindings(): $CancellablePromise<{ [_ in string]?: services$0.KeyboardAction }> {
    return $Call.ByID(122030866).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetKeyboardBindingsByCategory returns keyboard bindings grouped by category
 */
export function GetKeyboardBindingsByCategory(): $CancellablePromise<{ [_ in string]?: services$0.KeyboardAction[] }> {
    return $Call.ByID(1363231388).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * HandleKeyboardEvent handles keyboard events
 */
export function HandleKeyboardEvent(event: services$0.KeyboardEvent): $CancellablePromise<void> {
    return $Call.ByID(3917158859, event);
}

/**
 * ImportKeyboardBindings imports keyboard bindings
 */
export function ImportKeyboardBindings(bindings: { [_ in string]?: services$0.KeyboardAction }): $CancellablePromise<void> {
    return $Call.ByID(1545682240, bindings);
}

/**
 * RemoveKeyboardBinding removes a keyboard binding
 */
export function RemoveKeyboardBinding(key: string): $CancellablePromise<void> {
    return $Call.ByID(1740944284, key);
}

/**
 * ResetKeyboardBindings resets keyboard bindings to defaults
 */
export function ResetKeyboardBindings(): $CancellablePromise<void> {
    return $Call.ByID(2781976602);
}

// Private type creation functions
const $$createType0 = services$0.KeyboardAction.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
