// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsFileService handles file operations, dialogs, credentials, and utility functions for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * ClearRecentFiles clears the recent files list
 */
export function ClearRecentFiles(): $CancellablePromise<void> {
    return $Call.ByID(1164027236);
}

/**
 * CopyFile copies a file from source to destination
 */
export function CopyFile(srcPath: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(2793831170, srcPath, destPath);
}

/**
 * CreateDirectory creates a new directory
 */
export function CreateDirectory(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(3180973136, dirPath);
}

/**
 * CreateTempFile creates a temporary file with the given content
 */
export function CreateTempFile(content: string, prefix: string, suffix: string): $CancellablePromise<string> {
    return $Call.ByID(2949720849, content, prefix, suffix);
}

/**
 * DeleteFile deletes a file
 */
export function DeleteFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3129988124, filePath);
}

/**
 * DeletePassword deletes a password using the hybrid password manager
 */
export function DeletePassword(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2721512247, connectionID);
}

/**
 * FileExists checks if a file exists
 */
export function FileExists(filePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2829512675, filePath);
}

/**
 * GetAppIcon returns the main application icon
 */
export function GetAppIcon(): $CancellablePromise<string> {
    return $Call.ByID(4071446319).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetAppVersion returns the application version
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3205691054);
}

/**
 * GetDarkIcon returns the dark theme icon
 */
export function GetDarkIcon(): $CancellablePromise<string> {
    return $Call.ByID(16467694).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetDownloadsPath returns the user's downloads directory
 */
export function GetDownloadsPath(): $CancellablePromise<string> {
    return $Call.ByID(1916366023);
}

/**
 * GetFileInfo returns file information
 */
export function GetFileInfo(filePath: string): $CancellablePromise<services$0.FileInfo | null> {
    return $Call.ByID(1920610817, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetHomePath returns the user's home directory
 */
export function GetHomePath(): $CancellablePromise<string> {
    return $Call.ByID(3952801163);
}

/**
 * GetLightIcon returns the light theme icon
 */
export function GetLightIcon(): $CancellablePromise<string> {
    return $Call.ByID(3262843532).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetPassword retrieves a password using the hybrid password manager
 * connectionID is the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, tries keychain fallback
 */
export function GetPassword(connectionID: string, masterKeyBase64: string): $CancellablePromise<string> {
    return $Call.ByID(3097389166, connectionID, masterKeyBase64);
}

/**
 * GetRecentFiles returns recently accessed files
 */
export function GetRecentFiles(): $CancellablePromise<services$0.RecentFile[]> {
    return $Call.ByID(4173751507).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTempDir returns the system temporary directory
 */
export function GetTempDir(): $CancellablePromise<string> {
    return $Call.ByID(2739520496);
}

/**
 * GetWorkspaceFiles returns files in a workspace directory
 */
export function GetWorkspaceFiles(dirPath: string, extensions: string[]): $CancellablePromise<services$0.FileInfo[]> {
    return $Call.ByID(2610713531, dirPath, extensions).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HasPassword checks if a password exists in either keychain or encrypted DB
 * Returns true if the password exists, false otherwise
 */
export function HasPassword(connectionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2161521058, connectionID);
}

/**
 * OpenEnvFileDialog opens a file dialog for .env files and returns the selected file path and content
 */
export function OpenEnvFileDialog(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1112747406).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenFileDialog opens a file dialog and returns the selected file path
 */
export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(1122389771);
}

/**
 * ReadFile reads a file and returns its content
 */
export function ReadFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(143047699, filePath);
}

/**
 * RemoveFromRecentFiles removes a file from the recent files list
 */
export function RemoveFromRecentFiles(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3207503817, filePath);
}

/**
 * SaveFileDialog opens a save file dialog and returns the selected file path
 */
export function SaveFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(1467727518);
}

/**
 * SaveToDownloads saves content to a file in the downloads directory
 */
export function SaveToDownloads(filename: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(2910675050, filename, content);
}

/**
 * ShowErrorDialog shows an error dialog
 */
export function ShowErrorDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1256079434, title, message);
}

/**
 * ShowInfoDialog shows an information dialog
 */
export function ShowInfoDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3682785280, title, message);
}

/**
 * ShowNotification shows a notification dialog
 */
export function ShowNotification(title: string, message: string, isError: boolean): $CancellablePromise<void> {
    return $Call.ByID(2013254451, title, message, isError);
}

/**
 * ShowQuestionDialog shows a question dialog and returns the result
 */
export function ShowQuestionDialog(title: string, message: string): $CancellablePromise<boolean> {
    return $Call.ByID(1517545248, title, message);
}

/**
 * StorePassword stores a password securely using the hybrid password manager
 * connectionID is used as the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, uses keychain only (graceful degradation)
 */
export function StorePassword(connectionID: string, password: string, masterKeyBase64: string): $CancellablePromise<void> {
    return $Call.ByID(2636618051, connectionID, password, masterKeyBase64);
}

/**
 * WriteFile writes content to a file
 */
export function WriteFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3312018874, filePath, content);
}

// Private type creation functions
const $$createType0 = services$0.FileInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.RecentFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
