// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsAuthService handles authentication operations for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckBiometricAvailability checks if biometric authentication is available on the current platform
 */
export function CheckBiometricAvailability(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3538711116).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckStoredToken checks if a valid token exists for the specified provider
 */
export function CheckStoredToken(provider: string): $CancellablePromise<boolean> {
    return $Call.ByID(2836535881, provider);
}

/**
 * DeleteWebAuthnCredential removes a WebAuthn credential for a user
 */
export function DeleteWebAuthnCredential(userID: string): $CancellablePromise<void> {
    return $Call.ByID(2477866013, userID);
}

/**
 * FinishWebAuthnAuthentication completes the WebAuthn authentication process
 */
export function FinishWebAuthnAuthentication(userID: string, assertionJSON: string): $CancellablePromise<string> {
    return $Call.ByID(2916633992, userID, assertionJSON);
}

/**
 * FinishWebAuthnRegistration completes the WebAuthn registration process
 */
export function FinishWebAuthnRegistration(userID: string, credentialJSON: string): $CancellablePromise<boolean> {
    return $Call.ByID(3008225157, userID, credentialJSON);
}

/**
 * GetOAuthURL generates an OAuth authorization URL for the specified provider
 */
export function GetOAuthURL(provider: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1251098775, provider).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStoredUserInfo retrieves the stored user info for the specified provider
 */
export function GetStoredUserInfo(provider: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(97446987, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HasWebAuthnCredential checks if a user has registered WebAuthn credentials
 */
export function HasWebAuthnCredential(userID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3965016004, userID);
}

/**
 * Logout removes the stored token for the specified provider
 */
export function Logout(provider: string): $CancellablePromise<void> {
    return $Call.ByID(2264935083, provider);
}

/**
 * OnUrlOpen handles custom protocol URL callbacks (e.g., OAuth redirects)
 */
export function OnUrlOpen(url: string): $CancellablePromise<void> {
    return $Call.ByID(1600584045, url);
}

/**
 * StartWebAuthnAuthentication initiates the WebAuthn authentication process
 */
export function StartWebAuthnAuthentication(userID: string): $CancellablePromise<string> {
    return $Call.ByID(336966193, userID);
}

/**
 * StartWebAuthnRegistration initiates the WebAuthn registration process
 */
export function StartWebAuthnRegistration(userID: string, userName: string): $CancellablePromise<string> {
    return $Call.ByID(4259441192, userID, userName);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
