// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsReportService is a Wails-compatible service that wraps services.ReportService
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * DeleteReport removes a report definition
 */
export function DeleteReport(id: string): $CancellablePromise<void> {
    return $Call.ByID(864806236, id);
}

/**
 * GetReport loads a full report definition by ID
 */
export function GetReport(id: string): $CancellablePromise<storage$0.Report | null> {
    return $Call.ByID(561119925, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListReports returns summaries for all saved reports
 */
export function ListReports(): $CancellablePromise<storage$0.ReportSummary[]> {
    return $Call.ByID(1848559576).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RunReport executes all (or selected) components within a report
 */
export function RunReport(req: services$0.ReportRunRequest): $CancellablePromise<services$0.ReportRunResponse | null> {
    return $Call.ByID(1031713844, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveReport creates or updates a report definition
 */
export function SaveReport(report: storage$0.Report): $CancellablePromise<storage$0.Report | null> {
    return $Call.ByID(24920302, report).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = storage$0.Report.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.ReportSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = services$0.ReportRunResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
