// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsAIService handles all AI-related functionality for the Wails application
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearAIMemorySessions removes stored AI memory sessions
 */
export function ClearAIMemorySessions(): $CancellablePromise<void> {
    return $Call.ByID(429755306);
}

/**
 * ConfigureAIProvider configures an AI provider dynamically from UI
 */
export function ConfigureAIProvider(config: $models.ProviderConfig): $CancellablePromise<void> {
    return $Call.ByID(99807116, config);
}

/**
 * DeleteAIMemorySession removes a single session by ID
 */
export function DeleteAIMemorySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1342989077, sessionID);
}

/**
 * ExecuteReadOnlyQuery validates and executes a SELECT-only query with safety controls.
 */
export function ExecuteReadOnlyQuery(connectionID: string, query: string, maxRows: number, timeout: time$0.Duration): $CancellablePromise<$models.ReadOnlyQueryResult | null> {
    return $Call.ByID(3789884330, connectionID, query, maxRows, timeout).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteReadOnlyQueryWithPagination executes a SELECT query with pagination support.
 */
export function ExecuteReadOnlyQueryWithPagination(connectionID: string, query: string, pageSize: number, offset: number, timeout: time$0.Duration): $CancellablePromise<$models.ReadOnlyQueryResult | null> {
    return $Call.ByID(1345123230, connectionID, query, pageSize, offset, timeout).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FixSQLError attempts to fix a SQL error
 */
export function FixSQLError(query: string, error: string, connectionID: string): $CancellablePromise<$models.FixedSQLResponse | null> {
    return $Call.ByID(3412841426, query, error, connectionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FixSQLErrorWithOptions applies AI-based fixes with provider-specific configuration
 */
export function FixSQLErrorWithOptions(req: $models.FixSQLRequest): $CancellablePromise<$models.FixedSQLResponse | null> {
    return $Call.ByID(4233193456, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GenerateSQLFromNaturalLanguage generates SQL from a natural language prompt
 */
export function GenerateSQLFromNaturalLanguage(req: $models.NLQueryRequest): $CancellablePromise<$models.GeneratedSQLResponse | null> {
    return $Call.ByID(3647908673, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GenericChat handles generic conversational AI requests without SQL-specific expectations
 */
export function GenericChat(req: $models.GenericChatRequest): $CancellablePromise<$models.GenericChatResponse | null> {
    return $Call.ByID(2869227684, req).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetAIConfiguration returns the currently active AI provider configuration with masked secrets.
 */
export function GetAIConfiguration(): $CancellablePromise<$models.ProviderConfig> {
    return $Call.ByID(2663411021).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetAIProviderStatus returns the status of available AI providers
 */
export function GetAIProviderStatus(): $CancellablePromise<{ [_ in string]?: $models.ProviderStatus }> {
    return $Call.ByID(1623412826).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetAvailableModels returns the available models for a specific AI provider.
 * It queries the provider's API dynamically when possible, falling back to configured defaults.
 */
export function GetAvailableModels(provider: string): $CancellablePromise<$models.ModelInfoResponse[]> {
    return $Call.ByID(941444320, provider).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetQuerySuggestions provides autocomplete suggestions for a partial query
 */
export function GetQuerySuggestions(partialQuery: string, connectionID: string): $CancellablePromise<$models.Suggestion[]> {
    return $Call.ByID(3954589202, partialQuery, connectionID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * LoadAIMemorySessions retrieves previously stored AI memory sessions
 */
export function LoadAIMemorySessions(): $CancellablePromise<$models.AIMemorySessionPayload[]> {
    return $Call.ByID(3743481777).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * OptimizeQuery optimizes a SQL query
 */
export function OptimizeQuery(query: string, connectionID: string): $CancellablePromise<$models.OptimizationResponse | null> {
    return $Call.ByID(4270694066, query, connectionID).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RecallAIMemorySessions returns the most relevant stored memories for the given prompt
 */
export function RecallAIMemorySessions(prompt: string, limit: number): $CancellablePromise<$models.AIMemoryRecallResult[]> {
    return $Call.ByID(856876792, prompt, limit).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * SaveAIMemorySessions persists AI memory sessions and indexes them for recall
 */
export function SaveAIMemorySessions(sessions: $models.AIMemorySessionPayload[]): $CancellablePromise<void> {
    return $Call.ByID(1898149904, sessions);
}

/**
 * StartClaudeCodeLogin begins the Claude CLI login flow.
 */
export function StartClaudeCodeLogin(binaryPath: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(1423089201, binaryPath).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * StartCodexLogin begins the OpenAI CLI login flow for Codex access.
 */
export function StartCodexLogin(binaryPath: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(3927327559, binaryPath).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * StreamAIQueryAgent coordinates a multi-agent workflow to satisfy a user query.
 */
export function StreamAIQueryAgent(req: $models.AIQueryAgentRequest): $CancellablePromise<$models.AIQueryAgentResponse | null> {
    return $Call.ByID(4175428966, req).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * SuggestVisualization suggests appropriate visualizations for query results
 */
export function SuggestVisualization(resultData: $models.ResultData): $CancellablePromise<$models.VizSuggestion | null> {
    return $Call.ByID(3916004367, resultData).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * TestAIProvider tests a provider configuration without saving it
 */
export function TestAIProvider(config: $models.ProviderConfig): $CancellablePromise<$models.ProviderStatus | null> {
    return $Call.ByID(2859500718, config).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * TestAnthropicConnection tests Anthropic provider connection
 */
export function TestAnthropicConnection(apiKey: string, model: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(116921763, apiKey, model).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TestClaudeCodeConnection tests Claude Code provider connection
 */
export function TestClaudeCodeConnection(binaryPath: string, model: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(2783994514, binaryPath, model).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TestCodexConnection tests Codex provider connection
 */
export function TestCodexConnection(apiKey: string, model: string, organization: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(755689652, apiKey, model, organization).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TestHuggingFaceConnection tests HuggingFace provider connection
 */
export function TestHuggingFaceConnection(endpoint: string, model: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(4078595073, endpoint, model).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TestOllamaConnection tests Ollama provider connection
 */
export function TestOllamaConnection(endpoint: string, model: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(2814081267, endpoint, model).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TestOpenAIConnection tests OpenAI provider connection
 */
export function TestOpenAIConnection(apiKey: string, model: string): $CancellablePromise<$models.AITestResponse | null> {
    return $Call.ByID(182737427, apiKey, model).then(($result: any) => {
        return $$createType22($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ReadOnlyQueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FixedSQLResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GeneratedSQLResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GenericChatResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.ProviderConfig.createFrom;
const $$createType9 = $models.ProviderStatus.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = $models.ModelInfoResponse.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.Suggestion.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.AIMemorySessionPayload.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.OptimizationResponse.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.AIMemoryRecallResult.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.AITestResponse.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.AIQueryAgentResponse.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $models.VizSuggestion.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $Create.Nullable($$createType9);
