package schemadiff

import (
	"fmt"
	"strings"
	"time"

	"github.com/jbeck018/howlerops/backend-go/pkg/database"
)

// MigrationDirection specifies the direction of migration
type MigrationDirection string

const (
	MigrationForward  MigrationDirection = "forward"  // Source -> Target
	MigrationBackward MigrationDirection = "backward" // Target -> Source
)

// MigrationGenerator generates DDL migration scripts from schema diffs
type MigrationGenerator struct {
	dbType database.DatabaseType
}

// NewMigrationGenerator creates a new migration generator
func NewMigrationGenerator(dbType database.DatabaseType) *MigrationGenerator {
	return &MigrationGenerator{
		dbType: dbType,
	}
}

// GenerateSQL generates migration SQL from a schema diff
func (mg *MigrationGenerator) GenerateSQL(diff *SchemaDiff, direction MigrationDirection) (string, error) {
	var b strings.Builder

	// Write header
	mg.writeHeader(&b, diff, direction)

	// Generate SQL based on database type
	switch mg.dbType {
	case database.PostgreSQL, database.TiDB:
		mg.generatePostgresSQL(&b, diff, direction)
	case database.MySQL, database.MariaDB:
		mg.generateMySQLSQL(&b, diff, direction)
	case database.SQLite:
		mg.generateSQLiteSQL(&b, diff, direction)
	default:
		return "", fmt.Errorf("migration generation not supported for database type: %s", mg.dbType)
	}

	return b.String(), nil
}

// writeHeader writes the migration header
func (mg *MigrationGenerator) writeHeader(b *strings.Builder, diff *SchemaDiff, direction MigrationDirection) {
	b.WriteString("-- Migration generated by HowlerOps\n")
	b.WriteString(fmt.Sprintf("-- Source: %s\n", diff.SourceID))
	b.WriteString(fmt.Sprintf("-- Target: %s\n", diff.TargetID))
	b.WriteString(fmt.Sprintf("-- Direction: %s\n", direction))
	b.WriteString(fmt.Sprintf("-- Generated: %s\n", time.Now().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("-- Database Type: %s\n", mg.dbType))
	b.WriteString("\n")
}

// generatePostgresSQL generates PostgreSQL-compatible DDL
func (mg *MigrationGenerator) generatePostgresSQL(b *strings.Builder, diff *SchemaDiff, direction MigrationDirection) {
	for _, tableDiff := range diff.Tables {
		schema := tableDiff.Schema
		table := tableDiff.Name
		fullName := mg.quoteIdentifier(schema) + "." + mg.quoteIdentifier(table)

		switch tableDiff.Status {
		case DiffAdded:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("-- Add table: %s.%s\n", schema, table))
				b.WriteString("-- NOTE: Complete table structure needed from source schema\n")
				b.WriteString(fmt.Sprintf("-- CREATE TABLE %s (...);\n\n", fullName))
			} else {
				b.WriteString(fmt.Sprintf("-- Remove table: %s.%s\n", schema, table))
				b.WriteString(fmt.Sprintf("DROP TABLE IF EXISTS %s;\n\n", fullName))
			}

		case DiffRemoved:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("-- Remove table: %s.%s\n", schema, table))
				b.WriteString(fmt.Sprintf("DROP TABLE IF EXISTS %s;\n\n", fullName))
			} else {
				b.WriteString(fmt.Sprintf("-- Add table: %s.%s\n", schema, table))
				b.WriteString("-- NOTE: Complete table structure needed from target schema\n")
				b.WriteString(fmt.Sprintf("-- CREATE TABLE %s (...);\n\n", fullName))
			}

		case DiffModified:
			b.WriteString(fmt.Sprintf("-- Modify table: %s.%s\n", schema, table))
			mg.generatePostgresModifications(b, fullName, tableDiff, direction)
		}
	}
}

// generatePostgresModifications generates ALTER TABLE statements for PostgreSQL
func (mg *MigrationGenerator) generatePostgresModifications(b *strings.Builder, fullName string, tableDiff TableDiff, direction MigrationDirection) {
	// Column modifications
	for _, colDiff := range tableDiff.Columns {
		switch colDiff.Status {
		case DiffAdded:
			if direction == MigrationForward {
				nullable := "NULL"
				if colDiff.NewNull != nil && !*colDiff.NewNull {
					nullable = "NOT NULL"
				}
				defaultClause := ""
				if colDiff.NewDefault != nil && *colDiff.NewDefault != "" {
					defaultClause = fmt.Sprintf(" DEFAULT %s", *colDiff.NewDefault)
				}
				b.WriteString(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s%s;\n",
					fullName, mg.quoteIdentifier(colDiff.Name), colDiff.NewType, nullable, defaultClause))
			} else {
				b.WriteString(fmt.Sprintf("ALTER TABLE %s DROP COLUMN IF EXISTS %s;\n",
					fullName, mg.quoteIdentifier(colDiff.Name)))
			}

		case DiffRemoved:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("ALTER TABLE %s DROP COLUMN IF EXISTS %s;\n",
					fullName, mg.quoteIdentifier(colDiff.Name)))
			} else {
				nullable := "NULL"
				if colDiff.OldNull != nil && !*colDiff.OldNull {
					nullable = "NOT NULL"
				}
				defaultClause := ""
				if colDiff.OldDefault != nil && *colDiff.OldDefault != "" {
					defaultClause = fmt.Sprintf(" DEFAULT %s", *colDiff.OldDefault)
				}
				b.WriteString(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s%s;\n",
					fullName, mg.quoteIdentifier(colDiff.Name), colDiff.OldType, nullable, defaultClause))
			}

		case DiffModified:
			colName := mg.quoteIdentifier(colDiff.Name)
			if direction == MigrationForward {
				if colDiff.NewType != colDiff.OldType {
					b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
						fullName, colName, colDiff.NewType))
				}
				if colDiff.NewNull != nil && colDiff.OldNull != nil && *colDiff.NewNull != *colDiff.OldNull {
					if *colDiff.NewNull {
						b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;\n",
							fullName, colName))
					} else {
						b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;\n",
							fullName, colName))
					}
				}
			} else {
				if colDiff.OldType != colDiff.NewType {
					b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;\n",
						fullName, colName, colDiff.OldType))
				}
				if colDiff.OldNull != nil && colDiff.NewNull != nil && *colDiff.OldNull != *colDiff.NewNull {
					if *colDiff.OldNull {
						b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;\n",
							fullName, colName))
					} else {
						b.WriteString(fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;\n",
							fullName, colName))
					}
				}
			}
		}
	}

	// Index modifications
	for _, idxDiff := range tableDiff.Indexes {
		switch idxDiff.Status {
		case DiffAdded:
			if direction == MigrationForward {
				mg.generatePostgresCreateIndex(b, fullName, idxDiff, true)
			} else {
				b.WriteString(fmt.Sprintf("DROP INDEX IF EXISTS %s;\n", mg.quoteIdentifier(idxDiff.Name)))
			}

		case DiffRemoved:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("DROP INDEX IF EXISTS %s;\n", mg.quoteIdentifier(idxDiff.Name)))
			} else {
				mg.generatePostgresCreateIndex(b, fullName, idxDiff, false)
			}

		case DiffModified:
			// Drop and recreate
			b.WriteString(fmt.Sprintf("DROP INDEX IF EXISTS %s;\n", mg.quoteIdentifier(idxDiff.Name)))
			mg.generatePostgresCreateIndex(b, fullName, idxDiff, direction == MigrationForward)
		}
	}

	// Foreign key modifications
	for _, fkDiff := range tableDiff.ForeignKeys {
		switch fkDiff.Status {
		case DiffAdded:
			if direction == MigrationForward {
				mg.generatePostgresAddFK(b, fullName, fkDiff, true)
			} else {
				b.WriteString(fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s;\n",
					fullName, mg.quoteIdentifier(fkDiff.Name)))
			}

		case DiffRemoved:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s;\n",
					fullName, mg.quoteIdentifier(fkDiff.Name)))
			} else {
				mg.generatePostgresAddFK(b, fullName, fkDiff, false)
			}

		case DiffModified:
			// Drop and recreate
			b.WriteString(fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s;\n",
				fullName, mg.quoteIdentifier(fkDiff.Name)))
			mg.generatePostgresAddFK(b, fullName, fkDiff, direction == MigrationForward)
		}
	}

	b.WriteString("\n")
}

// generatePostgresCreateIndex generates CREATE INDEX statement
func (mg *MigrationGenerator) generatePostgresCreateIndex(b *strings.Builder, fullName string, idxDiff IndexDiff, useNew bool) {
	unique := ""
	var columns []string
	if useNew && idxDiff.NewUnique != nil && *idxDiff.NewUnique {
		unique = "UNIQUE "
	} else if !useNew && idxDiff.OldUnique != nil && *idxDiff.OldUnique {
		unique = "UNIQUE "
	}
	if useNew {
		columns = idxDiff.NewColumns
	} else {
		columns = idxDiff.OldColumns
	}

	quotedColumns := make([]string, len(columns))
	for i, col := range columns {
		quotedColumns[i] = mg.quoteIdentifier(col)
	}

	b.WriteString(fmt.Sprintf("CREATE %sINDEX %s ON %s (%s);\n",
		unique, mg.quoteIdentifier(idxDiff.Name), fullName, strings.Join(quotedColumns, ", ")))
}

// generatePostgresAddFK generates ADD CONSTRAINT for foreign key
func (mg *MigrationGenerator) generatePostgresAddFK(b *strings.Builder, fullName string, fkDiff FKDiff, useNew bool) {
	var columns, refColumns []string
	var refTable, onDelete, onUpdate string

	if useNew {
		columns = fkDiff.NewColumns
		refTable = fkDiff.NewRefTable
		refColumns = fkDiff.NewRefColumns
		onDelete = fkDiff.NewOnDelete
		onUpdate = fkDiff.NewOnUpdate
	} else {
		columns = fkDiff.OldColumns
		refTable = fkDiff.OldRefTable
		refColumns = fkDiff.OldRefColumns
		onDelete = fkDiff.OldOnDelete
		onUpdate = fkDiff.OldOnUpdate
	}

	quotedColumns := make([]string, len(columns))
	for i, col := range columns {
		quotedColumns[i] = mg.quoteIdentifier(col)
	}
	quotedRefColumns := make([]string, len(refColumns))
	for i, col := range refColumns {
		quotedRefColumns[i] = mg.quoteIdentifier(col)
	}

	b.WriteString(fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		fullName, mg.quoteIdentifier(fkDiff.Name),
		strings.Join(quotedColumns, ", "),
		mg.quoteIdentifier(refTable),
		strings.Join(quotedRefColumns, ", ")))

	if onDelete != "" {
		b.WriteString(fmt.Sprintf(" ON DELETE %s", onDelete))
	}
	if onUpdate != "" {
		b.WriteString(fmt.Sprintf(" ON UPDATE %s", onUpdate))
	}
	b.WriteString(";\n")
}

// generateMySQLSQL generates MySQL-compatible DDL
func (mg *MigrationGenerator) generateMySQLSQL(b *strings.Builder, diff *SchemaDiff, direction MigrationDirection) {
	// MySQL uses similar syntax to PostgreSQL with minor differences
	// For simplicity, reuse PostgreSQL logic with minor adjustments
	mg.generatePostgresSQL(b, diff, direction)
}

// generateSQLiteSQL generates SQLite-compatible DDL
func (mg *MigrationGenerator) generateSQLiteSQL(b *strings.Builder, diff *SchemaDiff, direction MigrationDirection) {
	b.WriteString("-- WARNING: SQLite has limited ALTER TABLE support\n")
	b.WriteString("-- Column modifications require table recreation\n\n")

	for _, tableDiff := range diff.Tables {
		table := tableDiff.Name
		fullName := mg.quoteIdentifier(table)

		switch tableDiff.Status {
		case DiffAdded:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("-- Add table: %s\n", table))
				b.WriteString(fmt.Sprintf("-- CREATE TABLE %s (...);\n\n", fullName))
			} else {
				b.WriteString(fmt.Sprintf("-- Remove table: %s\n", table))
				b.WriteString(fmt.Sprintf("DROP TABLE IF EXISTS %s;\n\n", fullName))
			}

		case DiffRemoved:
			if direction == MigrationForward {
				b.WriteString(fmt.Sprintf("-- Remove table: %s\n", table))
				b.WriteString(fmt.Sprintf("DROP TABLE IF EXISTS %s;\n\n", fullName))
			} else {
				b.WriteString(fmt.Sprintf("-- Add table: %s\n", table))
				b.WriteString(fmt.Sprintf("-- CREATE TABLE %s (...);\n\n", fullName))
			}

		case DiffModified:
			b.WriteString(fmt.Sprintf("-- Modify table: %s\n", table))
			b.WriteString(fmt.Sprintf("-- SQLite requires table recreation for most modifications\n"))
			b.WriteString(fmt.Sprintf("-- See: https://www.sqlite.org/lang_altertable.html\n\n"))
		}
	}
}

// quoteIdentifier quotes an identifier based on database type
func (mg *MigrationGenerator) quoteIdentifier(identifier string) string {
	switch mg.dbType {
	case database.PostgreSQL, database.TiDB:
		return `"` + identifier + `"`
	case database.MySQL, database.MariaDB:
		return "`" + identifier + "`"
	case database.SQLite:
		return `"` + identifier + `"`
	default:
		return identifier
	}
}

// MigrationScript represents a generated migration script
type MigrationScript struct {
	Direction    MigrationDirection    `json:"direction"`
	DatabaseType database.DatabaseType `json:"database_type"`
	SQL          string                `json:"sql"`
	GeneratedAt  time.Time             `json:"generated_at"`
	SourceID     string                `json:"source_id"`
	TargetID     string                `json:"target_id"`
}

// GenerateForwardScript generates a forward migration script (source -> target)
func (mg *MigrationGenerator) GenerateForwardScript(diff *SchemaDiff) (*MigrationScript, error) {
	sql, err := mg.GenerateSQL(diff, MigrationForward)
	if err != nil {
		return nil, err
	}

	return &MigrationScript{
		Direction:    MigrationForward,
		DatabaseType: mg.dbType,
		SQL:          sql,
		GeneratedAt:  time.Now(),
		SourceID:     diff.SourceID,
		TargetID:     diff.TargetID,
	}, nil
}

// GenerateReverseScript generates a reverse migration script (target -> source)
func (mg *MigrationGenerator) GenerateReverseScript(diff *SchemaDiff) (*MigrationScript, error) {
	sql, err := mg.GenerateSQL(diff, MigrationBackward)
	if err != nil {
		return nil, err
	}

	return &MigrationScript{
		Direction:    MigrationBackward,
		DatabaseType: mg.dbType,
		SQL:          sql,
		GeneratedAt:  time.Now(),
		SourceID:     diff.SourceID,
		TargetID:     diff.TargetID,
	}, nil
}
