// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ColumnDiff represents the diff for a single column
 */
export class ColumnDiff {
    "name": string;
    "status": DiffStatus;
    "old_type"?: string;
    "new_type"?: string;
    "old_nullable"?: boolean | null;
    "new_nullable"?: boolean | null;
    "old_default"?: string | null;
    "new_default"?: string | null;

    /** Creates a new ColumnDiff instance. */
    constructor($$source: Partial<ColumnDiff> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DiffStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDiff($$parsedSource as Partial<ColumnDiff>);
    }
}

/**
 * DiffStatus represents the status of a schema object in a diff
 */
export enum DiffStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DiffAdded = "added",
    DiffRemoved = "removed",
    DiffModified = "modified",
    DiffUnchanged = "unchanged",
};

/**
 * DiffSummary provides aggregate statistics about the diff
 */
export class DiffSummary {
    "tables_added": number;
    "tables_removed": number;
    "tables_modified": number;
    "columns_added": number;
    "columns_removed": number;
    "columns_modified": number;
    "indexes_changed": number;
    "fks_changed": number;

    /** Creates a new DiffSummary instance. */
    constructor($$source: Partial<DiffSummary> = {}) {
        if (!("tables_added" in $$source)) {
            this["tables_added"] = 0;
        }
        if (!("tables_removed" in $$source)) {
            this["tables_removed"] = 0;
        }
        if (!("tables_modified" in $$source)) {
            this["tables_modified"] = 0;
        }
        if (!("columns_added" in $$source)) {
            this["columns_added"] = 0;
        }
        if (!("columns_removed" in $$source)) {
            this["columns_removed"] = 0;
        }
        if (!("columns_modified" in $$source)) {
            this["columns_modified"] = 0;
        }
        if (!("indexes_changed" in $$source)) {
            this["indexes_changed"] = 0;
        }
        if (!("fks_changed" in $$source)) {
            this["fks_changed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffSummary($$parsedSource as Partial<DiffSummary>);
    }
}

/**
 * FKDiff represents the diff for a single foreign key
 */
export class FKDiff {
    "name": string;
    "status": DiffStatus;
    "old_columns"?: string[];
    "new_columns"?: string[];
    "old_ref_table"?: string;
    "new_ref_table"?: string;
    "old_ref_columns"?: string[];
    "new_ref_columns"?: string[];
    "old_on_delete"?: string;
    "new_on_delete"?: string;
    "old_on_update"?: string;
    "new_on_update"?: string;

    /** Creates a new FKDiff instance. */
    constructor($$source: Partial<FKDiff> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DiffStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FKDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): FKDiff {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("old_columns" in $$parsedSource) {
            $$parsedSource["old_columns"] = $$createField2_0($$parsedSource["old_columns"]);
        }
        if ("new_columns" in $$parsedSource) {
            $$parsedSource["new_columns"] = $$createField3_0($$parsedSource["new_columns"]);
        }
        if ("old_ref_columns" in $$parsedSource) {
            $$parsedSource["old_ref_columns"] = $$createField6_0($$parsedSource["old_ref_columns"]);
        }
        if ("new_ref_columns" in $$parsedSource) {
            $$parsedSource["new_ref_columns"] = $$createField7_0($$parsedSource["new_ref_columns"]);
        }
        return new FKDiff($$parsedSource as Partial<FKDiff>);
    }
}

/**
 * IndexDiff represents the diff for a single index
 */
export class IndexDiff {
    "name": string;
    "status": DiffStatus;
    "old_columns"?: string[];
    "new_columns"?: string[];
    "old_unique"?: boolean | null;
    "new_unique"?: boolean | null;
    "old_method"?: string;
    "new_method"?: string;

    /** Creates a new IndexDiff instance. */
    constructor($$source: Partial<IndexDiff> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DiffStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexDiff {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("old_columns" in $$parsedSource) {
            $$parsedSource["old_columns"] = $$createField2_0($$parsedSource["old_columns"]);
        }
        if ("new_columns" in $$parsedSource) {
            $$parsedSource["new_columns"] = $$createField3_0($$parsedSource["new_columns"]);
        }
        return new IndexDiff($$parsedSource as Partial<IndexDiff>);
    }
}

/**
 * MigrationDirection specifies the direction of migration
 */
export enum MigrationDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Source -> Target
     */
    MigrationForward = "forward",

    /**
     * Target -> Source
     */
    MigrationBackward = "backward",
};

/**
 * MigrationScript represents a generated migration script
 */
export class MigrationScript {
    "direction": MigrationDirection;
    "database_type": database$0.DatabaseType;
    "sql": string;
    "generated_at": time$0.Time;
    "source_id": string;
    "target_id": string;

    /** Creates a new MigrationScript instance. */
    constructor($$source: Partial<MigrationScript> = {}) {
        if (!("direction" in $$source)) {
            this["direction"] = MigrationDirection.$zero;
        }
        if (!("database_type" in $$source)) {
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("generated_at" in $$source)) {
            this["generated_at"] = null;
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("target_id" in $$source)) {
            this["target_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationScript instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationScript {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationScript($$parsedSource as Partial<MigrationScript>);
    }
}

/**
 * SchemaDiff represents the complete diff between two database schemas
 */
export class SchemaDiff {
    "source_id": string;
    "target_id": string;
    "timestamp": time$0.Time;
    "summary": DiffSummary;
    "tables": TableDiff[];
    "duration": time$0.Duration;

    /** Creates a new SchemaDiff instance. */
    constructor($$source: Partial<SchemaDiff> = {}) {
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("target_id" in $$source)) {
            this["target_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new DiffSummary());
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaDiff {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField4_0($$parsedSource["tables"]);
        }
        return new SchemaDiff($$parsedSource as Partial<SchemaDiff>);
    }
}

/**
 * SchemaSnapshot represents a saved point-in-time snapshot of a database schema
 */
export class SchemaSnapshot {
    "id": string;
    "name": string;
    "connection_id": string;
    "database_type": database$0.DatabaseType;
    "schemas": string[];
    "tables": { [_ in string]?: database$0.TableInfo[] };
    "structures": { [_ in string]?: database$0.TableStructure | null };
    "created_at": time$0.Time;
    "hash": string;

    /** Creates a new SchemaSnapshot instance. */
    constructor($$source: Partial<SchemaSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = "";
        }
        if (!("database_type" in $$source)) {
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("schemas" in $$source)) {
            this["schemas"] = [];
        }
        if (!("tables" in $$source)) {
            this["tables"] = {};
        }
        if (!("structures" in $$source)) {
            this["structures"] = {};
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaSnapshot {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schemas" in $$parsedSource) {
            $$parsedSource["schemas"] = $$createField4_0($$parsedSource["schemas"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("structures" in $$parsedSource) {
            $$parsedSource["structures"] = $$createField6_0($$parsedSource["structures"]);
        }
        return new SchemaSnapshot($$parsedSource as Partial<SchemaSnapshot>);
    }
}

/**
 * SnapshotMetadata provides lightweight snapshot info for listing
 */
export class SnapshotMetadata {
    "id": string;
    "name": string;
    "connection_id": string;
    "database_type": database$0.DatabaseType;
    "table_count": number;
    "created_at": time$0.Time;
    "size_bytes": number;

    /** Creates a new SnapshotMetadata instance. */
    constructor($$source: Partial<SnapshotMetadata> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = "";
        }
        if (!("database_type" in $$source)) {
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("table_count" in $$source)) {
            this["table_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): SnapshotMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotMetadata($$parsedSource as Partial<SnapshotMetadata>);
    }
}

/**
 * TableDiff represents the diff for a single table
 */
export class TableDiff {
    "schema": string;
    "name": string;
    "status": DiffStatus;
    "columns"?: ColumnDiff[];
    "indexes"?: IndexDiff[];
    "foreign_keys"?: FKDiff[];

    /** Creates a new TableDiff instance. */
    constructor($$source: Partial<TableDiff> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DiffStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDiff {
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField4_0($$parsedSource["indexes"]);
        }
        if ("foreign_keys" in $$parsedSource) {
            $$parsedSource["foreign_keys"] = $$createField5_0($$parsedSource["foreign_keys"]);
        }
        return new TableDiff($$parsedSource as Partial<TableDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DiffSummary.createFrom;
const $$createType2 = TableDiff.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = database$0.TableInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = database$0.TableStructure.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = ColumnDiff.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = IndexDiff.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = FKDiff.createFrom;
const $$createType15 = $Create.Array($$createType14);
