// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../pkg/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * EditableColumnResponse represents an editable column
 */
export class EditableColumnResponse {
    "name": string;
    "resultName": string;
    "dataType": string;
    "editable": boolean;
    "primaryKey": boolean;
    "foreignKey"?: ForeignKeyResponse | null;
    "hasDefault"?: boolean;
    "defaultValue"?: any;
    "defaultExpression"?: string;
    "autoNumber"?: boolean;
    "timeZone"?: boolean;
    "precision"?: number | null;

    /** Creates a new EditableColumnResponse instance. */
    constructor($$source: Partial<EditableColumnResponse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("resultName" in $$source)) {
            this["resultName"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditableColumnResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EditableColumnResponse {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("foreignKey" in $$parsedSource) {
            $$parsedSource["foreignKey"] = $$createField5_0($$parsedSource["foreignKey"]);
        }
        return new EditableColumnResponse($$parsedSource as Partial<EditableColumnResponse>);
    }
}

/**
 * EditableMetadataResponse represents editable metadata for queries
 */
export class EditableMetadataResponse {
    "enabled": boolean;
    "reason"?: string;
    "schema"?: string;
    "table"?: string;
    "primaryKeys": string[];
    "columns": EditableColumnResponse[];
    "pending": boolean;
    "jobId"?: string;
    "capabilities"?: database$0.MutationCapabilities | null;

    /** Creates a new EditableMetadataResponse instance. */
    constructor($$source: Partial<EditableMetadataResponse> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("primaryKeys" in $$source)) {
            this["primaryKeys"] = [];
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("pending" in $$source)) {
            this["pending"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditableMetadataResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EditableMetadataResponse {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField4_0($$parsedSource["primaryKeys"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField5_0($$parsedSource["columns"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        return new EditableMetadataResponse($$parsedSource as Partial<EditableMetadataResponse>);
    }
}

/**
 * FileInfo represents file metadata
 */
export class FileInfo {
    "name": string;
    "path": string;
    "size": number;
    "modTime": string;
    "isDirectory": boolean;
    "extension": string;
    "permissions": string;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * ForeignKeyResponse represents foreign key information
 */
export class ForeignKeyResponse {
    "table": string;
    "column": string;
    "schema"?: string;

    /** Creates a new ForeignKeyResponse instance. */
    constructor($$source: Partial<ForeignKeyResponse> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKeyResponse($$parsedSource as Partial<ForeignKeyResponse>);
    }
}

/**
 * ImportConnectionsResult contains the result of importing connections
 */
export class ImportConnectionsResult {
    "imported": number;
    "skipped": number;
    "errors": string[];

    /** Creates a new ImportConnectionsResult instance. */
    constructor($$source: Partial<ImportConnectionsResult> = {}) {
        if (!("imported" in $$source)) {
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConnectionsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportConnectionsResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new ImportConnectionsResult($$parsedSource as Partial<ImportConnectionsResult>);
    }
}

/**
 * ImportHistoryResult contains the result of importing history
 */
export class ImportHistoryResult {
    "imported": number;
    "skipped": number;
    "errors": string[];

    /** Creates a new ImportHistoryResult instance. */
    constructor($$source: Partial<ImportHistoryResult> = {}) {
        if (!("imported" in $$source)) {
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportHistoryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportHistoryResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new ImportHistoryResult($$parsedSource as Partial<ImportHistoryResult>);
    }
}

/**
 * ImportQueriesResult contains the result of importing queries
 */
export class ImportQueriesResult {
    "imported": number;
    "skipped": number;
    "errors": string[];

    /** Creates a new ImportQueriesResult instance. */
    constructor($$source: Partial<ImportQueriesResult> = {}) {
        if (!("imported" in $$source)) {
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportQueriesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportQueriesResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new ImportQueriesResult($$parsedSource as Partial<ImportQueriesResult>);
    }
}

/**
 * KeyboardAction represents a keyboard shortcut action
 */
export class KeyboardAction {
    "key": string;
    "description": string;
    "category": string;
    "handler": string;

    /** Creates a new KeyboardAction instance. */
    constructor($$source: Partial<KeyboardAction> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("handler" in $$source)) {
            this["handler"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardAction instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyboardAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardAction($$parsedSource as Partial<KeyboardAction>);
    }
}

/**
 * KeyboardEvent represents a keyboard event
 */
export class KeyboardEvent {
    "key": string;
    "ctrlKey": boolean;
    "altKey": boolean;
    "shiftKey": boolean;
    "metaKey": boolean;
    "timestamp": number;

    /** Creates a new KeyboardEvent instance. */
    constructor($$source: Partial<KeyboardEvent> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("ctrlKey" in $$source)) {
            this["ctrlKey"] = false;
        }
        if (!("altKey" in $$source)) {
            this["altKey"] = false;
        }
        if (!("shiftKey" in $$source)) {
            this["shiftKey"] = false;
        }
        if (!("metaKey" in $$source)) {
            this["metaKey"] = false;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyboardEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardEvent($$parsedSource as Partial<KeyboardEvent>);
    }
}

/**
 * MigrationStatus represents the current migration state
 */
export class MigrationStatus {
    "sqlite_has_data": boolean;
    "migration_done": boolean;
    "connection_count": number;
    "query_count": number;
    "history_count": number;
    "preferences_count": number;

    /** Creates a new MigrationStatus instance. */
    constructor($$source: Partial<MigrationStatus> = {}) {
        if (!("sqlite_has_data" in $$source)) {
            this["sqlite_has_data"] = false;
        }
        if (!("migration_done" in $$source)) {
            this["migration_done"] = false;
        }
        if (!("connection_count" in $$source)) {
            this["connection_count"] = 0;
        }
        if (!("query_count" in $$source)) {
            this["query_count"] = 0;
        }
        if (!("history_count" in $$source)) {
            this["history_count"] = 0;
        }
        if (!("preferences_count" in $$source)) {
            this["preferences_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationStatus($$parsedSource as Partial<MigrationStatus>);
    }
}

/**
 * RecentFile represents a recently opened file
 */
export class RecentFile {
    "path": string;
    "name": string;
    "lastOpened": string;
    "size": number;

    /** Creates a new RecentFile instance. */
    constructor($$source: Partial<RecentFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentFile instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentFile($$parsedSource as Partial<RecentFile>);
    }
}

/**
 * ReportComponentResult wraps query or LLM outputs.
 */
export class ReportComponentResult {
    "componentId": string;
    "type": storage$0.ReportComponentType;
    "columns"?: string[];
    "rows"?: any[][];
    "rowCount"?: number;
    "durationMs"?: number;
    "content"?: string;
    "metadata"?: { [_ in string]?: any };
    "error"?: string;
    "cacheHit"?: boolean;

    /**
     * Total before LIMIT
     */
    "totalRows"?: number;

    /**
     * Actual rows returned
     */
    "limitedRows"?: number;

    /** Creates a new ReportComponentResult instance. */
    constructor($$source: Partial<ReportComponentResult> = {}) {
        if (!("componentId" in $$source)) {
            this["componentId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = storage$0.ReportComponentType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportComponentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportComponentResult {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType8;
        const $$createField7_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new ReportComponentResult($$parsedSource as Partial<ReportComponentResult>);
    }
}

/**
 * ReportRunRequest represents a run invocation from the UI.
 */
export class ReportRunRequest {
    "reportId": string;
    "componentIds": string[];
    "filters": { [_ in string]?: any };
    "force": boolean;

    /** Creates a new ReportRunRequest instance. */
    constructor($$source: Partial<ReportRunRequest> = {}) {
        if (!("reportId" in $$source)) {
            this["reportId"] = "";
        }
        if (!("componentIds" in $$source)) {
            this["componentIds"] = [];
        }
        if (!("filters" in $$source)) {
            this["filters"] = {};
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportRunRequest {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("componentIds" in $$parsedSource) {
            $$parsedSource["componentIds"] = $$createField1_0($$parsedSource["componentIds"]);
        }
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField2_0($$parsedSource["filters"]);
        }
        return new ReportRunRequest($$parsedSource as Partial<ReportRunRequest>);
    }
}

/**
 * ReportRunResponse contains aggregated component data.
 */
export class ReportRunResponse {
    "reportId": string;
    "startedAt": time$0.Time;
    "completedAt": time$0.Time;
    "results": ReportComponentResult[];

    /** Creates a new ReportRunResponse instance. */
    constructor($$source: Partial<ReportRunResponse> = {}) {
        if (!("reportId" in $$source)) {
            this["reportId"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = null;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportRunResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportRunResponse {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new ReportRunResponse($$parsedSource as Partial<ReportRunResponse>);
    }
}

// Private type creation functions
const $$createType0 = ForeignKeyResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = EditableColumnResponse.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = database$0.MutationCapabilities.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = ReportComponentResult.createFrom;
const $$createType11 = $Create.Array($$createType10);
