// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ColumnInfo represents metadata about a table column
 */
export class ColumnInfo {
    "name": string;
    "data_type": string;
    "nullable": boolean;
    "default_value": string | null;
    "primary_key": boolean;
    "unique": boolean;
    "indexed": boolean;
    "comment": string;
    "ordinal_position": number;
    "character_maximum_length": number | null;
    "numeric_precision": number | null;
    "numeric_scale": number | null;
    "metadata": { [_ in string]?: string };

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("data_type" in $$source)) {
            this["data_type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("default_value" in $$source)) {
            this["default_value"] = null;
        }
        if (!("primary_key" in $$source)) {
            this["primary_key"] = false;
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("indexed" in $$source)) {
            this["indexed"] = false;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("ordinal_position" in $$source)) {
            this["ordinal_position"] = 0;
        }
        if (!("character_maximum_length" in $$source)) {
            this["character_maximum_length"] = null;
        }
        if (!("numeric_precision" in $$source)) {
            this["numeric_precision"] = null;
        }
        if (!("numeric_scale" in $$source)) {
            this["numeric_scale"] = null;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField12_0($$parsedSource["metadata"]);
        }
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * DatabaseType represents the type of database
 */
export enum DatabaseType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PostgreSQL = "postgresql",
    MySQL = "mysql",
    SQLite = "sqlite",
    MariaDB = "mariadb",
    Elasticsearch = "elasticsearch",
    OpenSearch = "opensearch",
    ClickHouse = "clickhouse",
    MongoDB = "mongodb",
    TiDB = "tidb",
};

/**
 * EditableColumn describes a column returned in a query and whether it is editable
 */
export class EditableColumn {
    "name": string;
    "result_name": string;
    "data_type": string;
    "editable": boolean;
    "primary_key": boolean;
    "foreign_key"?: ForeignKeyRef | null;
    "has_default"?: boolean;
    "default_value"?: any;
    "default_expression"?: string;
    "auto_number"?: boolean;
    "time_zone"?: boolean;
    "precision"?: number | null;

    /** Creates a new EditableColumn instance. */
    constructor($$source: Partial<EditableColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("result_name" in $$source)) {
            this["result_name"] = "";
        }
        if (!("data_type" in $$source)) {
            this["data_type"] = "";
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }
        if (!("primary_key" in $$source)) {
            this["primary_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditableColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): EditableColumn {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("foreign_key" in $$parsedSource) {
            $$parsedSource["foreign_key"] = $$createField5_0($$parsedSource["foreign_key"]);
        }
        return new EditableColumn($$parsedSource as Partial<EditableColumn>);
    }
}

/**
 * EditableQueryMetadata captures whether a query result set supports direct editing
 */
export class EditableQueryMetadata {
    "enabled": boolean;
    "reason"?: string;
    "schema"?: string;
    "table"?: string;
    "primary_keys"?: string[];
    "columns"?: EditableColumn[];
    "pending"?: boolean;
    "job_id"?: string;
    "capabilities"?: MutationCapabilities | null;

    /** Creates a new EditableQueryMetadata instance. */
    constructor($$source: Partial<EditableQueryMetadata> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditableQueryMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): EditableQueryMetadata {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        const $$createField8_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary_keys" in $$parsedSource) {
            $$parsedSource["primary_keys"] = $$createField4_0($$parsedSource["primary_keys"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField5_0($$parsedSource["columns"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        return new EditableQueryMetadata($$parsedSource as Partial<EditableQueryMetadata>);
    }
}

/**
 * ForeignKeyInfo represents metadata about a foreign key constraint
 */
export class ForeignKeyInfo {
    "name": string;
    "columns": string[];
    "referenced_table": string;
    "referenced_schema": string;
    "referenced_columns": string[];
    "on_delete": string;
    "on_update": string;

    /** Creates a new ForeignKeyInfo instance. */
    constructor($$source: Partial<ForeignKeyInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("referenced_table" in $$source)) {
            this["referenced_table"] = "";
        }
        if (!("referenced_schema" in $$source)) {
            this["referenced_schema"] = "";
        }
        if (!("referenced_columns" in $$source)) {
            this["referenced_columns"] = [];
        }
        if (!("on_delete" in $$source)) {
            this["on_delete"] = "";
        }
        if (!("on_update" in $$source)) {
            this["on_update"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyInfo {
        const $$createField1_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("referenced_columns" in $$parsedSource) {
            $$parsedSource["referenced_columns"] = $$createField4_0($$parsedSource["referenced_columns"]);
        }
        return new ForeignKeyInfo($$parsedSource as Partial<ForeignKeyInfo>);
    }
}

/**
 * ForeignKeyRef represents a foreign key reference for a column
 */
export class ForeignKeyRef {
    "table": string;
    "column": string;
    "schema"?: string;

    /** Creates a new ForeignKeyRef instance. */
    constructor($$source: Partial<ForeignKeyRef> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKeyRef($$parsedSource as Partial<ForeignKeyRef>);
    }
}

/**
 * IndexInfo represents metadata about a database index
 */
export class IndexInfo {
    "name": string;
    "columns": string[];
    "unique": boolean;
    "primary": boolean;
    "type": string;
    "method": string;
    "metadata": { [_ in string]?: string };

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("primary" in $$source)) {
            this["primary"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField1_0 = $$createType3;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField6_0($$parsedSource["metadata"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

/**
 * MutationCapabilities describes which row-level operations are supported.
 */
export class MutationCapabilities {
    "can_insert": boolean;
    "can_update": boolean;
    "can_delete": boolean;
    "reason"?: string;

    /** Creates a new MutationCapabilities instance. */
    constructor($$source: Partial<MutationCapabilities> = {}) {
        if (!("can_insert" in $$source)) {
            this["can_insert"] = false;
        }
        if (!("can_update" in $$source)) {
            this["can_update"] = false;
        }
        if (!("can_delete" in $$source)) {
            this["can_delete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MutationCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): MutationCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MutationCapabilities($$parsedSource as Partial<MutationCapabilities>);
    }
}

/**
 * PoolStats contains connection pool statistics
 */
export class PoolStats {
    "open_connections": number;
    "in_use": number;
    "idle": number;
    "wait_count": number;
    "wait_duration": time$0.Duration;
    "max_idle_closed": number;
    "max_idle_time_closed": number;
    "max_lifetime_closed": number;

    /** Creates a new PoolStats instance. */
    constructor($$source: Partial<PoolStats> = {}) {
        if (!("open_connections" in $$source)) {
            this["open_connections"] = 0;
        }
        if (!("in_use" in $$source)) {
            this["in_use"] = 0;
        }
        if (!("idle" in $$source)) {
            this["idle"] = 0;
        }
        if (!("wait_count" in $$source)) {
            this["wait_count"] = 0;
        }
        if (!("wait_duration" in $$source)) {
            this["wait_duration"] = time$0.Duration.$zero;
        }
        if (!("max_idle_closed" in $$source)) {
            this["max_idle_closed"] = 0;
        }
        if (!("max_idle_time_closed" in $$source)) {
            this["max_idle_time_closed"] = 0;
        }
        if (!("max_lifetime_closed" in $$source)) {
            this["max_lifetime_closed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PoolStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PoolStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PoolStats($$parsedSource as Partial<PoolStats>);
    }
}

/**
 * TableInfo represents metadata about a database table
 */
export class TableInfo {
    "schema": string;
    "name": string;
    "type": string;
    "comment": string;
    "created_at": time$0.Time | null;
    "updated_at": time$0.Time | null;
    "row_count": number;
    "size_bytes": number;
    "owner": string;
    "metadata": { [_ in string]?: string };

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("row_count" in $$source)) {
            this["row_count"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

/**
 * TableStructure represents the complete structure of a table
 */
export class TableStructure {
    "table": TableInfo;
    "columns": ColumnInfo[];
    "indexes": IndexInfo[];
    "foreign_keys": ForeignKeyInfo[];
    "triggers": string[];
    "statistics": { [_ in string]?: string };

    /** Creates a new TableStructure instance. */
    constructor($$source: Partial<TableStructure> = {}) {
        if (!("table" in $$source)) {
            this["table"] = (new TableInfo());
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            this["indexes"] = [];
        }
        if (!("foreign_keys" in $$source)) {
            this["foreign_keys"] = [];
        }
        if (!("triggers" in $$source)) {
            this["triggers"] = [];
        }
        if (!("statistics" in $$source)) {
            this["statistics"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableStructure instance from a string or object.
     */
    static createFrom($$source: any = {}): TableStructure {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("table" in $$parsedSource) {
            $$parsedSource["table"] = $$createField0_0($$parsedSource["table"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField2_0($$parsedSource["indexes"]);
        }
        if ("foreign_keys" in $$parsedSource) {
            $$parsedSource["foreign_keys"] = $$createField3_0($$parsedSource["foreign_keys"]);
        }
        if ("triggers" in $$parsedSource) {
            $$parsedSource["triggers"] = $$createField4_0($$parsedSource["triggers"]);
        }
        if ("statistics" in $$parsedSource) {
            $$parsedSource["statistics"] = $$createField5_0($$parsedSource["statistics"]);
        }
        return new TableStructure($$parsedSource as Partial<TableStructure>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ForeignKeyRef.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = EditableColumn.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = MutationCapabilities.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = TableInfo.createFrom;
const $$createType9 = ColumnInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = IndexInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ForeignKeyInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
