// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CatalogTag represents a reusable tag
 */
export class CatalogTag {
    "id": string;
    "name": string;
    "color": string;
    "description"?: string;
    "organization_id"?: string | null;
    "is_system": boolean;
    "created_at": time$0.Time;

    /** Creates a new CatalogTag instance. */
    constructor($$source: Partial<CatalogTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogTag instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogTag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogTag($$parsedSource as Partial<CatalogTag>);
    }
}

/**
 * ColumnCatalogEntry represents catalog metadata for a column
 */
export class ColumnCatalogEntry {
    "id": string;
    "table_catalog_id": string;
    "column_name": string;
    "description"?: string;
    "tags"?: string[];
    "pii_type"?: string | null;
    "pii_confidence"?: number | null;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new ColumnCatalogEntry instance. */
    constructor($$source: Partial<ColumnCatalogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("table_catalog_id" in $$source)) {
            this["table_catalog_id"] = "";
        }
        if (!("column_name" in $$source)) {
            this["column_name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnCatalogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnCatalogEntry {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new ColumnCatalogEntry($$parsedSource as Partial<ColumnCatalogEntry>);
    }
}

/**
 * SearchFilters represents search filtering options
 */
export class SearchFilters {
    "connection_id"?: string | null;
    "schema_name"?: string | null;
    "tags"?: string[];
    "organization_id"?: string | null;
    "limit"?: number;

    /** Creates a new SearchFilters instance. */
    constructor($$source: Partial<SearchFilters> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchFilters instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchFilters {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new SearchFilters($$parsedSource as Partial<SearchFilters>);
    }
}

/**
 * SearchResult represents a single search result
 */
export class SearchResult {
    /**
     * 'table' or 'column'
     */
    "type": string;
    "id": string;
    "connection_id": string;
    "schema_name": string;
    "table_name": string;
    "column_name"?: string;
    "description"?: string;
    "tags"?: string[];
    "relevance_score": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = "";
        }
        if (!("schema_name" in $$source)) {
            this["schema_name"] = "";
        }
        if (!("table_name" in $$source)) {
            this["table_name"] = "";
        }
        if (!("relevance_score" in $$source)) {
            this["relevance_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SearchResults represents a collection of search results
 */
export class SearchResults {
    "results": (SearchResult | null)[];
    "total": number;
    "query": string;

    /** Creates a new SearchResults instance. */
    constructor($$source: Partial<SearchResults> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResults instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResults {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SearchResults($$parsedSource as Partial<SearchResults>);
    }
}

/**
 * TableCatalogEntry represents catalog metadata for a table
 */
export class TableCatalogEntry {
    "id": string;
    "connection_id": string;
    "schema_name": string;
    "table_name": string;
    "description"?: string;
    "steward_user_id"?: string | null;
    "tags"?: string[];
    "organization_id"?: string | null;
    "columns"?: (ColumnCatalogEntry | null)[];
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "created_by": string;

    /** Creates a new TableCatalogEntry instance. */
    constructor($$source: Partial<TableCatalogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = "";
        }
        if (!("schema_name" in $$source)) {
            this["schema_name"] = "";
        }
        if (!("table_name" in $$source)) {
            this["table_name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableCatalogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TableCatalogEntry {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField8_0($$parsedSource["columns"]);
        }
        return new TableCatalogEntry($$parsedSource as Partial<TableCatalogEntry>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SearchResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ColumnCatalogEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
